# -*- coding: utf-8 -*-
"""CI/CD & GitOps technologies."""

TECH = {
"jenkins": {
  "name": "Jenkins", "category": "CI/CD",
  "role": "Jenkins est le serveur d'automatisation open-source de reference pour l'integration et la livraison continues. Il orchestre la compilation, les tests, le packaging et le deploiement via des pipelines declaratifs ou scriptes ecrits en Groovy (Jenkinsfile) et versionnes avec le code. Son ecosysteme de 1800+ plugins l'integre a Git, Docker, Kubernetes, les outils de qualite et les cloud providers. Les agents distribues permettent d'executer des milliers de jobs en parallele, et les Shared Libraries factorisent la logique de pipeline a l'echelle d'une organisation — un standard dans les environnements bancaires haute disponibilite.",
  "commands": [
    ("java -jar jenkins.war --httpPort=8080", "Lancer Jenkins en standalone"),
    ("jenkins-plugin-cli --plugins workflow-aggregator git docker-workflow", "Installer des plugins en CLI / Dockerfile"),
    ("java -jar jenkins-cli.jar -s http://host -auth user:token build JOB -f -v", "Declencher un job et suivre la sortie"),
    ("java -jar jenkins-cli.jar safe-restart", "Redemarrage propre apres fin des jobs"),
    ("curl -X POST http://host/job/JOB/build --user user:token", "Trigger via API REST"),
    ("curl http://host/job/JOB/lastBuild/api/json", "Etat du dernier build (JSON)"),
    ("pipeline { agent any; stages { stage('Build'){ steps { sh 'mvn -B package' } } } }", "Squelette de pipeline declaratif"),
    ("sh 'docker build -t reg/app:$BUILD_NUMBER .'", "Etape shell de build d'image"),
    ("withCredentials([usernamePassword(credentialsId:'reg', ...)]) { ... }", "Injection securisee de secrets"),
    ("library 'shared-lib@main'", "Charger une Shared Library versionnee"),
    ("input message: 'Deployer en PROD ?', submitter: 'release-mgr'", "Gate d'approbation manuelle"),
    ("post { failure { mail to:'ops@x', subject:'KO' } }", "Notification conditionnelle"),
    ("parallel(unit:{ sh 'mvn test' }, lint:{ sh 'mvn verify' })", "Stages paralleles"),
    ("java -jar jenkins-cli.jar list-jobs", "Lister les jobs configures"),
  ],
  "concepts": [
    "Le controller (master) orchestre, planifie et stocke la configuration ; les agents (anciennement slaves) executent les builds, isolant la charge et les toolchains par technologie.",
    "Le Jenkinsfile decrit le pipeline as code : syntaxe declarative (lisible, structuree en stages) ou scriptee (Groovy complet pour la logique avancee).",
    "Le Multibranch Pipeline detecte automatiquement les branches et Pull Requests d'un depot Git et instancie un pipeline par branche.",
    "Les Shared Libraries (vars/ et src/) factorisent la logique commune (build standard, scan securite, deploiement Helm) reutilisee par des centaines de pipelines.",
    "Les agents ephemeres Kubernetes/Docker creent un pod ou conteneur jetable par build, garantissant des environnements propres et reproductibles.",
    "Le modele de credentials (Secret text, username/password, SSH key, certificat) centralise les secrets, jamais en clair dans le Jenkinsfile.",
    "Les triggers : webhook SCM (push/PR), cron (H/15 * * * *), upstream/downstream, et evenements externes via API.",
  ],
  "install": [
    "Deploiement recommande en conteneur (image jenkins/jenkins:lts-jdk17) avec un volume persistant sur JENKINS_HOME et JCasC pour la configuration as code.",
    "Configuration as Code (plugin configuration-as-code) decrit securite, clouds, credentials et outils dans un YAML versionne — zero clic manuel.",
    "Provisionner les agents via le plugin Kubernetes : un pod template par type de build (maven, node, golang) avec limits CPU/RAM.",
    "Pre-installer les plugins de maniere deterministe via plugins.txt et jenkins-plugin-cli dans l'image Docker pour des builds reproductibles.",
    "Activer l'authentification (LDAP/SAML/OIDC) et la strategie d'autorisation matricielle ou role-based dès l'initialisation.",
  ],
  "cicd": [
    "Structurer le pipeline en stages explicites : Checkout, Build, Tests unitaires, Analyse qualite (SonarQube), Build image, Scan (Trivy), Push registry, Deploiement, Tests E2E.",
    "Paralleliser les tests longs (unitaires/integration/charge) avec le bloc parallel pour reduire le temps de cycle — gain typique 40-60%.",
    "Utiliser des stages conditionnels (when { branch 'main' }) pour ne deployer en production que depuis les branches protegees.",
    "Integrer une gate d'approbation (input) avant la PROD dans les contextes bancaires, avec submitter restreint a un role release.",
    "Publier les artefacts et rapports (JUnit, Allure, couverture) via les steps junit/publishHTML pour la tracabilite reglementaire.",
  ],
  "prod": [
    "Haute disponibilite : controller actif/passif derriere un load balancer, JENKINS_HOME sur stockage repliquee, sauvegardes regulieres testees.",
    "Scalabilite horizontale via agents Kubernetes auto-provisionnes : la file d'attente declenche la creation de pods a la demande.",
    "Limiter la retention des builds (logRotator) pour maitriser l'espace disque et les performances de l'UI.",
    "Surveiller la sante (metriques Prometheus via le plugin) : longueur de file, duree des builds, agents indisponibles, jobs en echec.",
    "Externaliser les logs de build et activer des timeouts par stage pour eviter les pipelines bloques qui saturent les agents.",
  ],
  "security": [
    "Ne jamais stocker de secret dans le Jenkinsfile : utiliser le credentials store et withCredentials, et masquer la sortie.",
    "Activer le sandbox Groovy et la script approval pour empecher l'execution de code arbitraire par des pipelines non fiables.",
    "Appliquer un RBAC strict (plugin Role Strategy) : separation build/deploy/admin, et restreindre les agents par equipe.",
    "Mettre a jour controller et plugins regulierement : les plugins sont la principale surface d'attaque (CVE frequentes).",
    "Isoler les builds non fiables (forks, PR externes) sur des agents dedies sans acces aux secrets de production — conformite PCI DSS.",
  ],
  "pitfalls": [
    "Pipeline scripte monolithique illisible : symptome de logique non factorisee — migrer vers declaratif + Shared Library.",
    "Builds 'flaky' dus a des agents partages avec etat residuel : passer aux agents ephemeres jetables.",
    "JENKINS_HOME qui explose en taille : configurer logRotator et nettoyer workspaces (cleanWs).",
    "Secrets exposes dans les logs : toujours utiliser withCredentials qui masque, jamais echo d'une variable sensible.",
    "Plugin hell : incompatibilites apres mise a jour — figer les versions via plugins.txt et tester sur une instance de staging.",
  ],
  "practices": [
    "Pipeline as Code versionne avec l'application : toute modification passe en revue de code et est tracable.",
    "Fail fast : ordonner les stages du moins cher au plus cher (lint -> unit -> integration -> E2E) pour echouer tot.",
    "Idempotence et rollback : chaque deploiement doit pouvoir etre rejoue et annule sans intervention manuelle.",
    "Shared Library testee unitairement (avec JenkinsPipelineUnit) et versionnee par tag — pas de @main en production.",
    "Observabilite du pipeline : exposer duree, taux d'echec et MTTR comme des KPI suivis dans Grafana.",
  ],
},

"gitlab-ci": {
  "name": "GitLab CI/CD", "category": "CI/CD",
  "role": "GitLab CI/CD est le moteur d'integration et de livraison continues integre nativement a GitLab. Le pipeline est decrit dans un fichier .gitlab-ci.yml versionne, execute par des Runners (shell, Docker, Kubernetes). Il couvre tout le cycle DevSecOps : build, tests, SAST/DAST, conteneurisation, environnements dynamiques (review apps), deploiements multi-stages et Auto DevOps. Son integration registre/Container Registry, environnements et approbations en fait une plateforme de bout en bout, largement utilisee pour industrialiser des dizaines d'applications Spring Boot sur Kubernetes.",
  "commands": [
    ("gitlab-runner register", "Enregistrer un runner aupres d'un projet/groupe"),
    ("gitlab-runner run", "Lancer le runner en mode foreground"),
    ("gitlab-runner verify --delete", "Verifier et purger les runners obsoletes"),
    ("gitlab-ci-local", "Executer le pipeline localement avant push"),
    ("stages: [build, test, deploy]", "Definir l'ordre des etapes"),
    ("script: - mvn -B package", "Commandes executees par un job"),
    ("rules: - if: '$CI_COMMIT_BRANCH == \"main\"'", "Conditionner l'execution d'un job"),
    ("artifacts: { paths: [target/*.jar], expire_in: 1 week }", "Conserver des artefacts"),
    ("cache: { key: $CI_COMMIT_REF_SLUG, paths: [.m2/] }", "Cache de dependances"),
    ("needs: [build]", "DAG : demarrer un job des qu'une dependance est prete"),
    ("environment: { name: prod, url: https://app }", "Declarer un environnement deployable"),
    ("include: { project: 'group/ci-templates', file: '/jobs.yml' }", "Reutiliser des templates CI"),
    ("trigger: { project: 'group/downstream' }", "Pipeline multi-projets"),
    ("CI_JOB_TOKEN / CI_REGISTRY", "Variables predefinies (auth registre)"),
  ],
  "concepts": [
    "Le pipeline est un graphe de jobs groupes en stages ; par defaut les stages s'executent en sequence, les jobs d'un stage en parallele.",
    "Les Runners executent les jobs : l'executor Docker fournit une image propre par job, l'executor Kubernetes provisionne un pod ephemere.",
    "rules/only/except controlent quand un job s'execute (branche, tag, MR, changements de fichiers, variables).",
    "needs cree un DAG : un job demarre des que ses dependances sont pretes, sans attendre tout le stage — pipelines plus rapides.",
    "Les environnements (review/staging/prod) tracent les deploiements, autorisent les approbations et le rollback en un clic.",
    "include + extends + !reference factorisent la configuration ; les CI/CD components packagent des pipelines reutilisables versionnes.",
    "Les variables (projet, groupe, instance, masquees/protegees) et le CI_JOB_TOKEN gerent secrets et authentification inter-projets.",
  ],
  "install": [
    "Installer gitlab-runner (paquet ou binaire), l'enregistrer avec un token de projet/groupe, choisir l'executor adapte (Docker recommande).",
    "Configurer config.toml : concurrent, limites, tags des runners, volumes Docker, cache distribue S3 pour des builds rapides.",
    "Pour Kubernetes, deployer le GitLab Runner via Helm avec autoscaling des pods de build selon la file.",
    "Definir un .gitlab-ci.yml minimal (stages, image par defaut, cache) puis enrichir par include de templates partages.",
    "Activer un cache distribue (S3/MinIO) et un registre proxy pour eviter de re-telecharger les dependances a chaque job.",
  ],
  "cicd": [
    "Modeliser un pipeline DevSecOps : build -> tests -> SAST/Secret Detection/Dependency Scanning -> build image -> scan container -> deploy.",
    "Utiliser des review apps : un environnement ephemere deploye par MR, detruit a la fermeture, pour valider avant merge.",
    "Promotion d'environnement via jobs manuels (when: manual) protegeant staging -> production avec approbation.",
    "Mutualiser la logique via CI/CD components/templates versionnes plutot que copier-coller le YAML entre 12+ applications.",
    "Parent-child et multi-project pipelines pour orchestrer des monorepos et des chaines de livraison inter-equipes.",
  ],
  "prod": [
    "Runners autoscalables (Kubernetes/Docker Machine) pour absorber les pics sans file d'attente, avec limits CPU/RAM par job.",
    "Cache distribue + registre proxy : reduction drastique du temps de pipeline et de la bande passante.",
    "Environnements proteges + approbations + deployment freeze pour les fenetres de gel bancaires.",
    "Surveiller la duree des pipelines, le taux d'echec et l'utilisation des runners (metriques exportees vers Prometheus/Grafana).",
    "Strategie de rollback : garder les images taggees par SHA et redeployer une version anterieure via l'API environnements.",
  ],
  "security": [
    "Variables masquees et protegees : les secrets ne s'affichent pas dans les logs et ne sont injectes que sur branches protegees.",
    "Activer SAST, Secret Detection, Dependency et Container Scanning natifs pour bloquer la livraison sur vulnerabilite critique.",
    "Restreindre le CI_JOB_TOKEN (scopes inter-projets) et utiliser des runners dedies pour les jobs touchant la production.",
    "Signer les images et appliquer un controle d'admission (cosign/policy) avant deploiement — chaine d'approvisionnement.",
    "Isoler les runners par niveau de sensibilite ; jamais de runner partage non taggue pour des pipelines manipulant des secrets PCI DSS.",
  ],
  "pitfalls": [
    "Pipelines lents car tout en sequence : introduire needs (DAG) et paralleliser les tests.",
    "Cache inefficace (mauvaise key) : utiliser une key stable par lockfile et des politiques pull/push adaptees.",
    "YAML duplique entre projets : centraliser via include/components versionnes.",
    "Jobs qui passent en local mais echouent en CI : figer l'image, ne pas dependre de l'etat du runner.",
    "Secrets fuites par echo ou artefact : utiliser variables masquees, ne jamais committer de .env.",
  ],
  "practices": [
    "Fail fast et stages ordonnes par cout ; lint et tests rapides avant build d'image.",
    "Un seul .gitlab-ci.yml lisible s'appuyant sur des templates testes et versionnes par tag.",
    "Immutabilite : taguer les images par CI_COMMIT_SHA et promouvoir le meme artefact d'un environnement a l'autre.",
    "Environnements declares pour tracabilite, approbations et rollback audit-friendly.",
    "Mesurer DORA metrics (lead time, deploy frequency, MTTR, change failure rate) a partir des donnees pipeline.",
  ],
},

"github-actions": {
  "name": "GitHub Actions", "category": "CI/CD",
  "role": "GitHub Actions est la plateforme d'automatisation et CI/CD integree a GitHub. Les workflows YAML places dans .github/workflows reagissent a des evenements (push, pull_request, schedule, workflow_dispatch) et s'executent sur des runners hebergees ou auto-hebergees. L'ecosysteme du Marketplace fournit des milliers d'actions reutilisables (build, tests, deploiement cloud, scan securite). Matrices, environnements avec approbations, OIDC pour un acces cloud sans secret de longue duree et reusable workflows en font un outil moderne pour livrer en continu, du portfolio statique aux microservices conteneurises.",
  "commands": [
    ("on: { push: { branches: [main] }, workflow_dispatch: {} }", "Declencheurs d'un workflow"),
    ("runs-on: ubuntu-latest", "Choisir le runner"),
    ("uses: actions/checkout@v4", "Recuperer le code"),
    ("uses: docker/build-push-action@v6", "Builder et pousser une image"),
    ("strategy: { matrix: { node: [18,20,22] } }", "Matrice de builds paralleles"),
    ("permissions: { contents: read, packages: write, id-token: write }", "Permissions minimales du token"),
    ("environment: production", "Environnement avec regles d'approbation"),
    ("secrets.GITHUB_TOKEN / secrets.MY_SECRET", "Acces aux secrets"),
    ("if: github.ref == 'refs/heads/main'", "Condition d'execution"),
    ("needs: [build]", "Dependance entre jobs"),
    ("uses: ./.github/workflows/reusable.yml", "Reusable workflow"),
    ("concurrency: { group: deploy, cancel-in-progress: true }", "Eviter les deploiements concurrents"),
    ("gh workflow run deploy.yml -f env=prod", "Declencher via GitHub CLI"),
    ("gh run watch", "Suivre l'execution en direct"),
  ],
  "concepts": [
    "Un workflow contient des jobs ; chaque job s'execute sur un runner et regroupe des steps (commandes shell ou actions reutilisables).",
    "Les evenements declencheurs vont du push/PR au cron (schedule), a l'appel manuel (workflow_dispatch) et aux evenements repo (issues, release).",
    "Les actions du Marketplace (composite, JavaScript, Docker) encapsulent une logique reutilisable et versionnee par tag/SHA.",
    "La matrice genere des combinaisons de jobs (OS x versions) pour tester largement en parallele.",
    "OIDC permet d'obtenir des credentials cloud court-vivants (AWS/GCP/Azure) sans stocker de cle longue duree.",
    "Les environnements ajoutent des reviewers obligatoires, des wait timers et des secrets dedies par cible (staging/prod).",
    "Reusable workflows et composite actions centralisent la logique commune entre depots d'une organisation.",
  ],
  "install": [
    "Aucune installation pour les runners GitHub-hosted ; pour les self-hosted, installer le runner agent et l'enregistrer (token repo/org).",
    "Structurer .github/workflows avec un fichier par finalite (ci.yml, deploy.yml, security.yml) et des reusable workflows partages.",
    "Definir permissions au plus juste au niveau workflow/job (principe du moindre privilege du GITHUB_TOKEN).",
    "Configurer les environnements (protection rules, required reviewers) avant tout job de deploiement production.",
    "Mettre en cache dependances (actions/cache ou cache integre setup-*) pour accelerer les builds.",
  ],
  "cicd": [
    "Pipeline type : checkout -> setup -> lint/test -> build image (buildx + cache GHA) -> push GHCR -> deploy via SSH/kubectl.",
    "Utiliser concurrency pour serialiser les deploiements et annuler les runs obsoletes sur une meme branche.",
    "Promotion via environnements : job deploy-staging automatique, deploy-prod soumis a required reviewers.",
    "Centraliser la logique de build/scan dans un reusable workflow appele par tous les services de l'organisation.",
    "Declencher des deploiements multi-serveurs via appleboy/ssh-action puis purge CDN et health-check en jobs dependants.",
  ],
  "prod": [
    "Runners self-hosted autoscalables (ARC sur Kubernetes) pour les charges lourdes ou besoins reseau internes.",
    "Cache type=gha pour Docker buildx : builds incrementaux rapides et reproductibles.",
    "Jobs idempotents avec git reset --hard origin/main + docker compose pull/up pour des deploiements deterministes.",
    "Health-check post-deploy (curl -fsS) et purge cache CDN comme jobs dependants du deploiement.",
    "Surveiller la consommation de minutes et la duree des workflows ; alerter sur les echecs de la branche principale.",
  ],
  "security": [
    "Privilegier OIDC plutot que des cles cloud statiques ; restreindre la confiance par sujet (repo:org/name:ref).",
    "Epingler les actions tierces par SHA (pas @v3 mutable) pour se premunir d'une compromission de la supply chain.",
    "permissions minimales du GITHUB_TOKEN ; secrets d'environnement isoles, jamais exposes aux forks (pull_request_target prudent).",
    "Scanner avec CodeQL et integrer Trivy/Dependency Review pour bloquer les vulnerabilites avant merge.",
    "Approbations obligatoires sur l'environnement production et runners self-hosted dedies pour les jobs sensibles.",
  ],
  "pitfalls": [
    "Actions tierces non epinglees : risque d'execution de code malveillant — epingler par SHA.",
    "pull_request_target mal utilise exposant des secrets aux PR de forks.",
    "Deploiements concurrents qui se telescopent : ajouter un bloc concurrency.",
    "Builds lents sans cache buildx/dependances : activer le cache GHA.",
    "GITHUB_TOKEN trop permissif par defaut : declarer permissions explicitement.",
  ],
  "practices": [
    "Least privilege systematique (permissions) et OIDC pour le cloud.",
    "Reusable workflows + actions epinglees par SHA, versionnees et testees.",
    "Un workflow lisible par finalite, jobs avec needs pour un DAG clair.",
    "Environnements proteges, approbations et health-check obligatoires avant de declarer un deploiement reussi.",
    "Mesurer lead time et taux d'echec via l'API runs pour piloter l'amelioration continue.",
  ],
},

"argocd": {
  "name": "ArgoCD", "category": "GitOps",
  "role": "Argo CD est le controleur GitOps declaratif de reference pour Kubernetes. Il surveille en continu un depot Git contenant l'etat desire (manifests, Helm, Kustomize) et reconcilie le cluster pour qu'il converge vers cet etat. Git devient l'unique source de verite : tout changement est un commit revu, audite et reversible par git revert. ArgoCD apporte la visualisation temps reel de l'arborescence des ressources, le drift detection, les sync waves, les rollouts progressifs et la gestion multi-clusters — pilier d'une approche GitOps end-to-end pour des environnements bancaires.",
  "commands": [
    ("argocd login HOST --sso", "S'authentifier sur le serveur Argo CD"),
    ("argocd app create app --repo URL --path k8s --dest-namespace ns --dest-server URL", "Creer une Application"),
    ("argocd app sync app", "Forcer la synchronisation vers l'etat Git"),
    ("argocd app get app", "Etat de sante et de sync d'une application"),
    ("argocd app diff app", "Comparer l'etat live et l'etat Git"),
    ("argocd app history app", "Historique des deploiements"),
    ("argocd app rollback app 12", "Revenir a une revision anterieure"),
    ("argocd app set app --sync-policy automated --self-heal", "Activer la reconciliation automatique"),
    ("argocd app wait app --health", "Bloquer jusqu'a etat Healthy"),
    ("argocd cluster add CONTEXT", "Enregistrer un cluster cible"),
    ("argocd repo add URL --username u --password p", "Declarer un depot Git"),
    ("kubectl apply -f application.yaml", "Creer une App via CRD (App of Apps)"),
    ("argocd appset create applicationset.yaml", "Generer des apps en masse (ApplicationSet)"),
    ("argocd app set app -p image.tag=$SHA", "Surcharger un parametre Helm"),
  ],
  "concepts": [
    "Le modele : etat desire en Git, etat live dans le cluster ; le controleur reconcilie en continu et expose un status Synced/OutOfSync + Healthy.",
    "L'Application CRD reference un depot, un chemin/revision et une destination (cluster + namespace) ; tout est declaratif et versionne.",
    "self-heal annule automatiquement les changements manuels sur le cluster (drift) pour revenir a l'etat Git.",
    "Le pattern App of Apps et les ApplicationSet generent et gerent des dizaines d'applications/clusters depuis une definition unique.",
    "Sync waves et hooks (PreSync/PostSync) ordonnent les deploiements (migrations DB avant l'app, par exemple).",
    "Outils supportes nativement : manifests bruts, Helm, Kustomize, jsonnet — sans pousser depuis le CI (pull model).",
    "RBAC projet : les AppProjects cloisonnent depots, destinations et permissions par equipe.",
  ],
  "install": [
    "Installer via manifests officiels ou Helm dans le namespace argocd ; exposer le serveur via Ingress + SSO (OIDC).",
    "Declarer depots et clusters de facon declarative (Secrets labelises) plutot qu'en CLI imperative.",
    "Structurer un repo GitOps : environnements (dev/staging/prod) en overlays Kustomize ou values Helm distinctes.",
    "Mettre en place l'App of Apps racine geree elle-meme par Argo CD (bootstrap declaratif du cluster).",
    "Activer notifications (Slack/Teams/email) sur evenements sync/health pour la tracabilite operationnelle.",
  ],
  "cicd": [
    "Le CI construit, teste et pousse l'image puis met a jour le tag dans le repo GitOps (commit) ; Argo CD deploie — separation build/deploy.",
    "Argo CD Image Updater ou un job CI qui bump le tag automatisent la promotion sans pipeline push vers le cluster.",
    "Promotion d'environnement = Pull Request entre overlays ; l'approbation de la PR vaut approbation de deploiement (auditable).",
    "Integrer argocd app wait --health dans une etape de verification post-promotion pour un feedback synchrone.",
    "Coupler a Argo Rollouts pour des strategies canary/blue-green pilotees par metriques.",
  ],
  "prod": [
    "Multi-clusters : un controleur central gere des clusters distants enregistres, avec sharding pour la mise a l'echelle.",
    "Self-heal + automated sync garantissent la convergence et eliminent la derive de configuration en production.",
    "HA : repliques du repo-server/application-controller, Redis HA, et limites de ressources adaptees au nombre d'apps.",
    "Drift detection comme controle de conformite continue — essentiel en environnement audite/bancaire.",
    "Rollback instantane par git revert : la procedure de reprise est un commit, tracable et reproductible.",
  ],
  "security": [
    "SSO/OIDC + RBAC fin via AppProjects : restreindre depots, destinations et actions (sync/override) par role.",
    "Chiffrer les secrets en Git (Sealed Secrets, SOPS, External Secrets) — jamais de secret en clair dans le repo GitOps.",
    "Signer les commits/tags et exiger des PR approuvees : la securite du deploiement devient la securite de Git.",
    "Limiter les clusters et namespaces autorises par projet pour contenir le rayon d'impact.",
    "Auditer toutes les syncs (qui, quoi, quand) via l'historique Argo CD + l'historique Git — conformite PCI DSS.",
  ],
  "pitfalls": [
    "OutOfSync permanent du a des mutations par des controleurs (HPA, webhooks) : utiliser ignoreDifferences.",
    "Secrets en clair dans Git : adopter Sealed Secrets/SOPS avant tout passage en production.",
    "App of Apps non bootstrappee correctement : l'app racine doit etre auto-geree.",
    "Sync waves manquantes : migrations DB qui s'executent apres l'app — ordonner via hooks/waves.",
    "RBAC trop large : un projet default ouvert a tout depot/cluster casse le cloisonnement.",
  ],
  "practices": [
    "Git unique source de verite ; aucune modification kubectl manuelle en production (self-heal actif).",
    "Repo GitOps separe du code applicatif, structure par environnement et par equipe.",
    "Secrets toujours chiffres (SOPS/Sealed Secrets/External Secrets).",
    "Promotion par PR revue : tracabilite et reversibilite natives.",
    "Sante et drift exposes en metriques/alerting pour une conformite continue.",
  ],
},

"flux": {
  "name": "Flux CD", "category": "GitOps",
  "role": "Flux CD est un ensemble de controleurs GitOps natifs Kubernetes (projet CNCF gradue) qui synchronisent l'etat du cluster avec des sources Git, OCI ou Helm. Architecture modulaire (source-controller, kustomize-controller, helm-controller, notification-controller, image-automation) pilotee entierement par des Custom Resources. Flux excelle pour la gestion declarative multi-tenant et multi-clusters, l'automatisation des mises a jour d'images et l'integration profonde avec Kustomize et Helm — une approche GitOps legere, composable et securisee.",
  "commands": [
    ("flux bootstrap github --owner=ORG --repository=fleet --path=clusters/prod", "Installer Flux et versionner sa propre conf"),
    ("flux check --pre", "Verifier les prerequis du cluster"),
    ("flux create source git app --url=URL --branch=main", "Declarer une source Git"),
    ("flux create kustomization app --source=GitRepository/app --path=./k8s --prune=true", "Reconcilier un overlay Kustomize"),
    ("flux create helmrelease app --chart=app --source=HelmRepository/repo", "Deployer un chart Helm"),
    ("flux reconcile kustomization app --with-source", "Forcer une reconciliation immediate"),
    ("flux get kustomizations -A", "Etat de toutes les kustomizations"),
    ("flux suspend / resume kustomization app", "Geler / reprendre la reconciliation"),
    ("flux create image repository app --image=reg/app", "Suivre les tags d'une image"),
    ("flux create image policy app --select-semver='>=1.0.0'", "Politique de selection de version"),
    ("flux trace deployment/app", "Remonter de la ressource au commit Git"),
    ("flux logs --follow --level=error", "Logs des controleurs"),
  ],
  "concepts": [
    "Architecture en controleurs specialises (sources, kustomize, helm, notification, image-automation) — composable et extensible.",
    "GitRepository/OCIRepository/HelmRepository sont des Sources ; Kustomization et HelmRelease decrivent quoi appliquer.",
    "Reconciliation pull-based avec intervalle configurable ; prune supprime les ressources retirees de Git.",
    "Image automation : Flux met a jour automatiquement les tags dans Git selon une policy semver/regex, puis commit.",
    "Multi-tenant : isolation par namespace, ServiceAccount et sourceRef restreints — adapte au fleet management.",
    "notification-controller emet alertes (Slack/Teams) et recoit des webhooks pour declencher des reconciliations.",
    "Flux se gere lui-meme : bootstrap commit sa propre configuration dans le repo (auto-update controle).",
  ],
  "install": [
    "flux bootstrap cree la structure clusters/<env>, installe les controleurs et versionne leur configuration en Git.",
    "Organiser un repo 'fleet' : infrastructure, sources, et applications par cluster/environnement.",
    "Definir des dependances entre Kustomizations (dependsOn) pour ordonner infra -> apps.",
    "Activer image-reflector/automation controllers pour les mises a jour d'images automatisees.",
    "Configurer notification-controller (Provider + Alert) des l'installation pour l'observabilite GitOps.",
  ],
  "cicd": [
    "Le CI publie l'image ; Flux image-automation detecte le nouveau tag, met a jour Git et reconcilie — zero push cluster.",
    "Promotion par environnement via dossiers/branches et dependsOn ; la PR est la porte d'approbation.",
    "postBuild substitute injecte des variables d'environnement dans les manifests sans dupliquer les fichiers.",
    "Health checks et wait dans les Kustomizations pour un feedback de deploiement deterministe.",
    "Coupler a Flagger pour des deploiements canary pilotes par metriques Prometheus.",
  ],
  "prod": [
    "Multi-clusters via repo fleet : un dossier par cluster, reconciliation independante et isolee.",
    "prune=true garantit l'absence de ressources orphelines ; l'etat reel ne diverge jamais de Git.",
    "Intervalles et timeouts ajustes pour limiter la charge API tout en gardant une convergence rapide.",
    "Suspend/resume cible pour les operations de maintenance sans desactiver tout le GitOps.",
    "Tracabilite complete : flux trace relie chaque ressource live au commit qui l'a produite.",
  ],
  "security": [
    "Secrets chiffres via SOPS (decryption native par kustomize-controller) ou External Secrets — jamais en clair.",
    "Multi-tenant securise : sourceRef cross-namespace desactive, ServiceAccounts dedies, RBAC strict.",
    "Verification de signature OCI/Cosign des artefacts avant application (supply chain).",
    "Acces Git en lecture seule par deploy key dediee et a portee minimale.",
    "Tout changement passe par Git signe et revue de PR — surface d'attaque reduite, audit natif.",
  ],
  "pitfalls": [
    "prune oublie : ressources orphelines persistantes — activer prune avec prudence et labels.",
    "dependsOn manquant : apps deployees avant l'infra (CRDs/namespaces).",
    "Secrets non chiffres pousses en Git : integrer SOPS des le depart.",
    "Boucle d'image-automation mal bornee (policy trop large) : restreindre par semver/regex.",
    "Reconciliation trop frequente saturant l'API server : ajuster les intervalles.",
  ],
  "practices": [
    "Repo fleet structure, Flux auto-gere (bootstrap), tout declaratif.",
    "Secrets via SOPS/External Secrets, signature des artefacts.",
    "dependsOn et health checks pour des deploiements ordonnes et fiables.",
    "Multi-tenant cloisonne par namespace/RBAC/ServiceAccount.",
    "Alerting GitOps (notification-controller) et flux trace pour l'auditabilite.",
  ],
},
}
