# -*- coding: utf-8 -*-
"""Conteneurisation & orchestration."""

TECH = {
"docker": {
  "name": "Docker", "category": "Conteneurisation",
  "role": "Docker est la plateforme de conteneurisation qui packetise une application et ses dependances dans une image immuable, portable et reproductible, executee de maniere isolee via les namespaces et cgroups du noyau Linux. Le Dockerfile decrit la construction de l'image, le registre la distribue, et le runtime garantit qu'un conteneur se comporte identiquement du poste developpeur a la production. Docker est le socle de l'industrialisation moderne : builds reproductibles, environnements de test jetables et microservices deployes sur Kubernetes.",
  "commands": [
    ("docker build -t reg/app:1.2.0 .", "Construire une image depuis un Dockerfile"),
    ("docker buildx build --platform linux/amd64,linux/arm64 --push -t reg/app .", "Build multi-arch"),
    ("docker run -d --name app -p 8080:8080 --env-file .env reg/app", "Lancer un conteneur detache"),
    ("docker exec -it app sh", "Ouvrir un shell dans un conteneur"),
    ("docker logs -f --tail 100 app", "Suivre les logs"),
    ("docker ps / docker ps -a", "Conteneurs actifs / tous"),
    ("docker images / docker image prune -af", "Lister / purger les images"),
    ("docker system df / docker system prune -af", "Espace disque / nettoyage"),
    ("docker tag app:1.2.0 reg/app:latest && docker push reg/app:latest", "Taguer et publier"),
    ("docker inspect app", "Metadonnees detaillees (JSON)"),
    ("docker stats", "Consommation CPU/RAM en direct"),
    ("docker scan / trivy image reg/app:1.2.0", "Scanner les vulnerabilites"),
  ],
  "concepts": [
    "Une image est une pile de couches en lecture seule (layers) ; le conteneur ajoute une couche ecriture ephemere par-dessus.",
    "Le cache de build reutilise les couches inchangees : l'ordre des instructions du Dockerfile conditionne la vitesse.",
    "L'isolation repose sur les namespaces (PID, net, mnt) et cgroups (limites CPU/RAM), pas sur une VM — d'ou la legerete.",
    "Le registre (Harbor, GHCR, ECR) stocke et distribue les images taggees, idealement par digest immuable.",
    "Les volumes persistent les donnees hors du cycle de vie du conteneur ; les bind mounts montent un chemin hote.",
    "Le multi-stage build separe l'environnement de compilation de l'image finale minimale (runtime).",
  ],
  "install": [
    "Installer Docker Engine (paquet officiel) + buildx ; activer le daemon, ajouter l'utilisateur au groupe docker (ou rootless).",
    "Configurer /etc/docker/daemon.json : log-driver json-file avec rotation, registres, storage driver overlay2.",
    "Ecrire un Dockerfile multi-stage : base epinglee par digest, dependances en couche separee, image finale distroless/alpine.",
    "Definir un .dockerignore strict pour reduire le contexte de build (exclure node_modules, .git, secrets).",
    "Mettre en place un registre proxy/cache et l'authentification (docker login) pour des builds CI rapides et fiables.",
  ],
  "cicd": [
    "Build reproductible en CI avec buildx + cache distant (type=gha, registry) : builds incrementaux rapides.",
    "Taguer chaque image par SHA de commit (immuable) et un alias mouvant (latest) reserve au staging.",
    "Scanner l'image (Trivy) et echouer le pipeline sur vulnerabilite critique avant push registry.",
    "Promotion par digest : le meme artefact exact transite de staging a production, jamais rebuild.",
    "Conteneuriser aussi les environnements de test (selenium, db) pour des suites E2E reproductibles.",
  ],
  "prod": [
    "Images minimales (distroless/alpine, multi-stage) : moins de surface d'attaque, demarrage rapide, pull plus leger.",
    "Limites cgroups (--memory, --cpus) et healthchecks pour des conteneurs previsibles et auto-redemarrables.",
    "Stockage des donnees sur volumes geres/externes ; les conteneurs restent stateless et jetables.",
    "Rotation des logs (json-file max-size/max-file) ou redirection vers un agent (Loki/ELK).",
    "Politique de pull par digest en production pour garantir l'immuabilite de ce qui tourne reellement.",
  ],
  "security": [
    "Ne jamais tourner en root : USER non privilegie, capabilities droppees, read-only rootfs quand possible.",
    "Pas de secret dans l'image ni en ARG : injection au runtime (env/secret manager), .dockerignore strict.",
    "Images de base epinglees par digest et scannees regulierement (Trivy) ; reconstruire sur CVE.",
    "Signer les images (cosign) et appliquer une admission policy pour n'executer que des images de confiance.",
    "Rootless/daemonless (Podman compatible) et seccomp/apparmor pour durcir l'isolation — exigences PCI DSS.",
  ],
  "pitfalls": [
    "Images obeses (1Go+) car build mono-stage : adopter le multi-stage et une base mince.",
    "Cache invalide a chaque build car COPY . . trop tot : copier d'abord les manifests de dependances.",
    "Conteneur en root expose : definir USER et droper les capabilities.",
    "Donnees perdues car ecrites dans la couche conteneur : utiliser des volumes.",
    "latest en production : non reproductible — deployer par digest.",
  ],
  "practices": [
    "Multi-stage, base epinglee par digest, image finale minimale et non-root.",
    "Un processus par conteneur, stateless, configuration par variables d'environnement.",
    "Tag immuable par SHA, scan systematique, promotion par digest.",
    ".dockerignore strict et ordre du Dockerfile optimise pour le cache.",
    "Healthcheck, limites de ressources et logs externalises.",
  ],
},

"kubernetes": {
  "name": "Kubernetes", "category": "Conteneurisation",
  "role": "Kubernetes (K8s) est l'orchestrateur de conteneurs standard de l'industrie. Il automatise le deploiement, la mise a l'echelle, l'auto-reparation et la mise en reseau d'applications conteneurisees a travers un cluster de noeuds. Son modele declaratif (objets YAML reconcilies en continu par des controleurs) garantit que l'etat reel converge vers l'etat desire. Services, Ingress, ConfigMaps/Secrets, autoscaling et RBAC en font la plateforme de reference pour exploiter des microservices bancaires en haute disponibilite.",
  "commands": [
    ("kubectl get pods -A -o wide", "Lister les pods de tous les namespaces"),
    ("kubectl apply -f manifests/ ", "Appliquer/mettre a jour des ressources"),
    ("kubectl describe pod POD", "Diagnostiquer events et etat d'un pod"),
    ("kubectl logs -f deploy/app -c app", "Logs d'un conteneur"),
    ("kubectl exec -it POD -- sh", "Shell dans un conteneur"),
    ("kubectl rollout status/undo deploy/app", "Suivre / annuler un deploiement"),
    ("kubectl scale deploy/app --replicas=5", "Mise a l'echelle manuelle"),
    ("kubectl get events --sort-by=.lastTimestamp", "Evenements recents tries"),
    ("kubectl top pod / node", "Consommation CPU/RAM"),
    ("kubectl port-forward svc/app 8080:80", "Acceder a un service en local"),
    ("kubectl create secret generic s --from-literal=k=v", "Creer un secret"),
    ("kubectl auth can-i create deploy --as user", "Verifier un droit RBAC"),
  ],
  "concepts": [
    "Le plan de controle (api-server, scheduler, controller-manager, etcd) decide ; les kubelets sur les noeuds executent.",
    "Le Pod est l'unite deployable (un ou plusieurs conteneurs partageant reseau/volumes) ; il est ephemere.",
    "Deployment gere des ReplicaSets pour des mises a jour progressives (rolling update) et des rollbacks.",
    "Service (ClusterIP/NodePort/LoadBalancer) + Ingress exposent et equilibrent le trafic de maniere stable.",
    "ConfigMap/Secret externalisent la configuration ; requests/limits pilotent l'ordonnancement et la QoS.",
    "Probes liveness/readiness/startup gouvernent le redemarrage et la mise en service d'un pod.",
    "HPA/VPA/Cluster Autoscaler ajustent automatiquement repliques et capacite selon la charge.",
  ],
  "install": [
    "Cluster gere (EKS/GKE/AKS) en production ; kubeadm/k3s pour on-prem ; kind/minikube en local.",
    "Structurer les manifests par environnement via Kustomize overlays ou charts Helm parametres.",
    "Definir namespaces, ResourceQuota et LimitRange par equipe/environnement des l'initialisation.",
    "Installer un Ingress Controller (NGINX/Traefik), cert-manager (TLS), et un CNI conforme aux NetworkPolicies.",
    "Mettre en place RBAC, comptes de service dedies et stockage (StorageClass) avant les charges applicatives.",
  ],
  "cicd": [
    "Le CI construit/scanne l'image ; le CD applique des manifests versionnes (GitOps via Argo CD/Flux).",
    "kubectl rollout status en gate de pipeline pour un feedback de deploiement synchrone et fiable.",
    "Strategies avancees : canary/blue-green via Argo Rollouts/Flagger pilotees par metriques.",
    "Promotion immuable par digest d'image ; aucune reconstruction entre environnements.",
    "Rollback declaratif (kubectl rollout undo ou git revert en GitOps) pour une reprise rapide.",
  ],
  "prod": [
    "Haute dispo : repliques multiples, PodDisruptionBudget, anti-affinite, etalement multi-AZ.",
    "Autoscaling combine HPA (charge) + Cluster Autoscaler (capacite) pour absorber les pics.",
    "Requests/limits realistes et QoS Guaranteed pour les services critiques bancaires.",
    "Observabilite : metrics-server + Prometheus, logs centralises (Loki/ELK), tracing distribue.",
    "Drains et rolling node upgrades maitrises pour des maintenances sans interruption.",
  ],
  "security": [
    "RBAC au moindre privilege, comptes de service dedies, pas de cluster-admin applicatif.",
    "NetworkPolicies en deny par defaut ; segmentation est-ouest entre namespaces.",
    "Pod Security Standards (restricted) : non-root, readOnlyRootFilesystem, capabilities droppees.",
    "Secrets chiffres at rest (etcd) + gestion externe (Vault/External Secrets), jamais en clair en Git.",
    "Admission control (OPA/Kyverno) et images signees ; audit logs actives — conformite PCI DSS.",
  ],
  "pitfalls": [
    "Pas de requests/limits : eviction et noisy neighbor — definir des valeurs realistes.",
    "Readiness probe absente : trafic route vers des pods non prets.",
    "Secrets en clair dans des ConfigMaps ou en Git : utiliser Secret + chiffrement externe.",
    "latest comme tag d'image : deploiements non reproductibles.",
    "NetworkPolicies absentes : trafic est-ouest totalement ouvert.",
  ],
  "practices": [
    "Tout declaratif et versionne (GitOps) ; aucun kubectl edit en production.",
    "Probes completes, requests/limits, PDB et anti-affinite pour la resilience.",
    "Namespaces + quotas + RBAC + NetworkPolicies pour le cloisonnement multi-tenant.",
    "Images immuables par digest, signees et scannees.",
    "Observabilite et autoscaling pilotes par metriques.",
  ],
},

"helm": {
  "name": "Helm", "category": "Conteneurisation",
  "role": "Helm est le gestionnaire de paquets de Kubernetes. Il empaquette un ensemble de manifests dans un Chart parametrable et versionne, instancie en Releases via des values surchargeables par environnement. Templating Go, dependances de charts, hooks de cycle de vie, rollback atomique et depots de charts industrialisent le deploiement repetable d'applications complexes sur des dizaines de clusters — un standard pour livrer des microservices bancaires de maniere homogene.",
  "commands": [
    ("helm create app", "Generer le squelette d'un chart"),
    ("helm lint app/", "Valider la structure et le templating"),
    ("helm template app/ -f values-prod.yaml", "Rendre les manifests sans installer"),
    ("helm install app app/ -n ns -f values-prod.yaml", "Installer une release"),
    ("helm upgrade --install app app/ -f values.yaml --atomic --wait", "Deploiement idempotent atomique"),
    ("helm diff upgrade app app/ -f values.yaml", "Previsualiser les changements (plugin diff)"),
    ("helm rollback app 3", "Revenir a une revision"),
    ("helm history app", "Historique des releases"),
    ("helm get values app", "Values effectives d'une release"),
    ("helm dependency update app/", "Resoudre les sous-charts"),
    ("helm package app/ && helm push app-1.0.0.tgz oci://reg/charts", "Publier un chart OCI"),
    ("helm repo add r URL && helm repo update", "Gerer les depots de charts"),
  ],
  "concepts": [
    "Un Chart = templates + values.yaml + Chart.yaml ; le rendu produit des manifests Kubernetes valides.",
    "Le moteur de templates Go (avec Sprig) injecte des valeurs, conditions et boucles dans les manifests.",
    "Une Release est une instance versionnee d'un chart dans un namespace ; chaque upgrade cree une revision.",
    "values.yaml par defaut surchargees par -f values-<env>.yaml ou --set : un chart, N environnements.",
    "Les dependances (Chart.yaml) composent des charts ; les hooks ordonnent migrations et jobs annexes.",
    "_helpers.tpl factorise les labels/noms ; la coherence des metadonnees est cle pour les selectors.",
  ],
  "install": [
    "Installer le binaire helm v3 (sans Tiller) ; configurer les depots ou un registre OCI prive (Harbor).",
    "Structurer un chart : templates parametres, values par defaut sures, values-<env> minimalistes.",
    "Versionner chart (version) et appVersion ; publier les charts packages dans un registre OCI immuable.",
    "Ajouter helm-diff et helm-secrets (SOPS) pour previsualisation et gestion des valeurs sensibles.",
    "Definir des schemas values.schema.json pour valider les entrees avant deploiement.",
  ],
  "cicd": [
    "helm lint + helm template + kubeconform en CI pour valider avant tout deploiement.",
    "helm upgrade --install --atomic --wait : deploiement idempotent qui s'auto-annule en cas d'echec.",
    "helm diff en revue de PR pour visualiser l'impact reel d'un changement de values.",
    "Charts publies en OCI et references par digest pour une promotion immuable entre environnements.",
    "En GitOps, Argo CD/Flux consomment le chart + values ; le CI ne fait que publier le chart.",
  ],
  "prod": [
    "--atomic + --wait + timeouts : un upgrade rate revient automatiquement a l'etat precedent.",
    "Rollback en une commande (helm rollback) trace par helm history — reprise rapide et auditable.",
    "Values d'environnement minimalistes (overrides) pour limiter la derive et les erreurs.",
    "Charts versionnes/immutables : reproductibilite exacte d'un deploiement passe.",
    "Limiter la retention des revisions (--history-max) pour eviter la surcharge des secrets de release.",
  ],
  "security": [
    "Valeurs sensibles chiffrees (helm-secrets/SOPS) ou injectees via External Secrets — jamais en clair.",
    "Charts signes (provenance) et tires depuis un registre de confiance ; scan des images referencees.",
    "RBAC du compte de deploiement au moindre privilege ; pas de cluster-admin pour Helm.",
    "Schema values strict pour empecher des surcharges dangereuses (privileged, hostPath).",
    "Auditer les releases (history) — tracabilite reglementaire des changements de configuration.",
  ],
  "pitfalls": [
    "Indentation/templating casse non detecte : systematiser helm lint + helm template en CI.",
    "Secrets en clair dans values : adopter SOPS/helm-secrets/External Secrets.",
    "upgrade non atomique laissant la release dans un etat incoherent : utiliser --atomic.",
    "Charts non versionnes (latest) : promotion non reproductible.",
    "Helpers incoherents cassant les selectors lors d'un rename : centraliser via _helpers.tpl.",
  ],
  "practices": [
    "Un chart parametre, values-<env> minimalistes, schema de validation.",
    "upgrade --install --atomic --wait, rollback documente.",
    "Charts versionnes/OCI immuables, signes et scannes.",
    "helm lint/template/diff systematiques en CI et en revue de PR.",
    "Secrets externalises et RBAC minimal.",
  ],
},

"docker-compose": {
  "name": "Docker Compose", "category": "Conteneurisation",
  "role": "Docker Compose definit et execute des applications multi-conteneurs via un fichier YAML declaratif (compose.yaml). Il orchestre services, reseaux, volumes et dependances en une commande, garantissant un environnement reproductible identique pour le developpement, les tests d'integration et les petits deploiements de production sur un hote unique. C'est l'outil de reference pour stacker une application, sa base de donnees et ses dependances sans la complexite d'un orchestrateur complet.",
  "commands": [
    ("docker compose up -d", "Demarrer la stack en arriere-plan"),
    ("docker compose up -d --build", "Reconstruire puis demarrer"),
    ("docker compose pull", "Recuperer les images a jour"),
    ("docker compose ps", "Etat des services"),
    ("docker compose logs -f --tail 100 svc", "Suivre les logs d'un service"),
    ("docker compose exec svc sh", "Shell dans un service"),
    ("docker compose down --remove-orphans", "Arreter et nettoyer"),
    ("docker compose config", "Valider et resoudre le fichier final"),
    ("docker compose -f compose.yaml -f compose.prod.yaml up -d", "Superposer des overrides"),
    ("docker compose run --rm svc cmd", "Lancer une tache ponctuelle"),
    ("docker compose restart svc", "Redemarrer un service"),
    ("docker compose --profile test up", "Activer un profil de services"),
  ],
  "concepts": [
    "Un service = une image + sa configuration ; Compose gere le cycle de vie de l'ensemble en une commande.",
    "Reseau par defaut dedie : les services se resolvent par nom DNS, isolant la stack.",
    "depends_on + healthcheck/condition ordonnent le demarrage selon la disponibilite reelle.",
    "Volumes nommes pour la persistance ; bind mounts pour le hot-reload en developpement.",
    "Override files (compose.override/prod.yaml) adaptent la stack par environnement sans dupliquer.",
    "Profiles activent des sous-ensembles de services (tests, outils) a la demande.",
  ],
  "install": [
    "Compose v2 est integre a Docker (plugin) : aucune installation separee, commande docker compose.",
    "Structurer compose.yaml (base) + compose.prod.yaml (override prod) ; variables via .env.",
    "Definir healthchecks et depends_on condition: service_healthy pour un demarrage fiable.",
    "Nommer volumes/reseaux explicitement pour la persistance et l'isolation inter-stacks.",
    "Epingler les images par tag/digest pour la reproductibilite.",
  ],
  "cicd": [
    "Stack de tests d'integration jetable : docker compose up -d, suite E2E, docker compose down.",
    "Deploiement sur hote unique en CD : git pull + docker compose pull + up -d --remove-orphans.",
    "config valide le fichier en CI avant deploiement (lint de stack).",
    "Profiles pour separer services applicatifs et services de test dans le meme fichier.",
    "Tag immuable par SHA pour que le CD deploie exactement l'artefact construit.",
  ],
  "prod": [
    "Adapte aux petits deploiements mono-hote ; healthchecks + restart: unless-stopped pour la resilience.",
    "Override prod : suppression des bind mounts/dev, ajout de limites de ressources et logs rotates.",
    "Sauvegarde des volumes nommes integree a la procedure d'exploitation.",
    "docker compose pull/up -d --remove-orphans = strategie de mise a jour deterministe.",
    "Au-dela d'un hote / besoin d'autoscaling : migrer vers Kubernetes.",
  ],
  "security": [
    "Secrets via variables d'environnement injectees (jamais committer .env) ou Docker secrets.",
    "Conteneurs non-root, capabilities reduites, read-only quand possible.",
    "Images epinglees et scannees (Trivy) avant deploiement.",
    "Reseau dedie et ports exposes au strict necessaire (pas de bind 0.0.0.0 inutile).",
    "Override prod sans outils de debug ni montages du code source.",
  ],
  "pitfalls": [
    "Course au demarrage (app avant DB) : utiliser healthcheck + depends_on condition.",
    ".env committe exposant des secrets : l'ajouter au .gitignore.",
    "Bind mounts de dev laisses en production : isoler via override.",
    "Images latest non reproductibles : epingler par digest.",
    "Volumes anonymes perdus au down -v : nommer les volumes a conserver.",
  ],
  "practices": [
    "compose.yaml + overrides par environnement, .env hors Git.",
    "Healthchecks + depends_on condition pour un demarrage ordonne.",
    "Images epinglees/scannees, conteneurs non-root.",
    "Volumes nommes sauvegardes ; restart policies adaptees.",
    "config en CI ; migrer vers K8s au-dela du mono-hote.",
  ],
},

"k3s": {
  "name": "K3s", "category": "Conteneurisation",
  "role": "K3s est une distribution Kubernetes certifiee CNCF, ultra-legere (binaire unique < 100 Mo), concue pour l'edge, l'IoT, le CI et les environnements a ressources contraintes. Elle remplace etcd par une base embarquee (SQLite/embedded etcd), integre conteneur runtime, CNI, Ingress (Traefik) et load balancer, tout en restant 100% compatible avec l'API Kubernetes. Ideale pour des clusters de test reproductibles, des PoC et des deploiements on-prem multi-noeuds simples a operer.",
  "commands": [
    ("curl -sfL https://get.k3s.io | sh -", "Installer un serveur K3s mono-noeud"),
    ("curl -sfL https://get.k3s.io | K3S_URL=https://srv:6443 K3S_TOKEN=t sh -", "Joindre un agent"),
    ("k3s kubectl get nodes", "kubectl integre"),
    ("cat /var/lib/rancher/k3s/server/node-token", "Recuperer le token de join"),
    ("k3s server --cluster-init", "Initialiser un cluster HA (embedded etcd)"),
    ("k3s-uninstall.sh / k3s-agent-uninstall.sh", "Desinstaller serveur / agent"),
    ("systemctl status k3s", "Etat du service"),
    ("k3s kubectl apply -f app.yaml", "Deployer une charge"),
    ("INSTALL_K3S_EXEC='--disable traefik' ...", "Desactiver des composants par defaut"),
    ("k3s ctr images ls", "Images du runtime containerd embarque"),
    ("kubectl get svc -n kube-system traefik", "Ingress Traefik integre"),
    ("k3s etcd-snapshot save", "Snapshot du datastore (HA)"),
  ],
  "concepts": [
    "Binaire unique embarquant API server, scheduler, controller, kubelet, containerd, Flannel CNI et Traefik.",
    "Datastore pluggable : SQLite (mono-noeud), embedded etcd (HA), ou backend externe (MySQL/Postgres).",
    "100% conforme a l'API Kubernetes : les manifests/Helm/kubectl fonctionnent a l'identique.",
    "Composants par defaut (Traefik, ServiceLB, local-path) desactivables selon le besoin.",
    "Empreinte memoire/CPU reduite : adapte a l'edge, aux VMs modestes et au CI ephemere.",
    "Token de join unique pour ajouter agents/serveurs ; bootstrap simplifie.",
  ],
  "install": [
    "Une commande pour le serveur ; les agents joignent via K3S_URL + K3S_TOKEN.",
    "HA : 3 serveurs avec --cluster-init/embedded etcd derriere un VIP/LB pour l'API.",
    "Desactiver les composants non desires (--disable traefik/servicelb) si une stack maison est preferee.",
    "Configurer un StorageClass adapte (local-path par defaut, ou Longhorn pour la persistance repartie).",
    "Automatiser l'installation via Ansible pour des clusters reproductibles multi-noeuds.",
  ],
  "cicd": [
    "Cluster K3s ephemere en pipeline (dans un conteneur/VM) pour des tests d'integration Kubernetes realistes.",
    "k3d (K3s-in-Docker) cree/detruit des clusters jetables en secondes pour la CI.",
    "Deploiement GitOps (Argo CD/Flux) identique a un cluster classique grace a la conformite API.",
    "Snapshots etcd avant upgrade pour un rollback rapide.",
    "Promotion d'images par digest comme sur tout cluster Kubernetes.",
  ],
  "prod": [
    "HA via 3 noeuds serveurs embedded etcd ; agents ajoutes a chaud selon la charge.",
    "Sauvegardes regulieres du datastore (k3s etcd-snapshot) testees pour la reprise.",
    "Empreinte reduite = cout d'exploitation faible pour l'edge/on-prem.",
    "Mises a jour controlees (system-upgrade-controller) noeud par noeud.",
    "Observabilite identique (Prometheus/Grafana/Loki) — pas de specificite operationnelle.",
  ],
  "security": [
    "RBAC, NetworkPolicies et Pod Security identiques a Kubernetes upstream.",
    "Token de join protege ; rotation et acces restreint au node-token.",
    "Chiffrement des secrets at rest et gestion externe (Vault/External Secrets).",
    "Surface reduite (binaire unique) mais maintien a jour indispensable (CVE noyau/runtime).",
    "Durcissement hote (CIS) car K3s est souvent sur des noeuds edge moins isoles.",
  ],
  "pitfalls": [
    "SQLite mono-noeud en production : pas de HA — passer en embedded etcd 3 serveurs.",
    "Traefik/ServiceLB par defaut en conflit avec une stack Ingress maison : desactiver explicitement.",
    "Stockage local-path non repartie : prevoir Longhorn/CSI pour la persistance HA.",
    "Token de join expose : compromission du cluster.",
    "Snapshots etcd non testes : reprise illusoire.",
  ],
  "practices": [
    "HA embedded etcd (3 serveurs) en production, snapshots testes.",
    "Desactiver les composants par defaut non utilises.",
    "Installation automatisee (Ansible/k3d) et reproductible.",
    "Securite K8s standard (RBAC/NetworkPolicy/secrets chiffres).",
    "Observabilite et GitOps identiques a un cluster classique.",
  ],
},

"harbor": {
  "name": "Harbor", "category": "Conteneurisation",
  "role": "Harbor est un registre de conteneurs open-source (projet CNCF gradue) de niveau entreprise. Il stocke et distribue images OCI et charts Helm avec controle d'acces RBAC par projet, scan de vulnerabilites integre (Trivy), signature et politique d'admission (Cosign/Notation), replication multi-registres, retention et quotas. C'est la piece centrale d'une chaine d'approvisionnement logicielle securisee : seules des images scannees, signees et conformes sont promues vers la production bancaire.",
  "commands": [
    ("docker login harbor.example.com", "S'authentifier au registre"),
    ("docker tag app:1.0 harbor.example.com/team/app:1.0", "Taguer pour Harbor"),
    ("docker push harbor.example.com/team/app:1.0", "Publier une image"),
    ("helm registry login harbor.example.com", "Auth pour charts OCI"),
    ("helm push app-1.0.0.tgz oci://harbor.example.com/charts", "Publier un chart"),
    ("docker pull harbor.example.com/team/app@sha256:...", "Tirer par digest immuable"),
    ("curl -u u:p https://harbor/api/v2.0/projects", "API : lister les projets"),
    ("curl .../api/v2.0/projects/ID/repositories", "Inventaire des depots"),
    ("trivy image harbor.example.com/team/app:1.0", "Scan complementaire local"),
    ("cosign sign --key k harbor.example.com/team/app:1.0", "Signer une image"),
    ("cosign verify --key k harbor.example.com/team/app:1.0", "Verifier la signature"),
    ("curl .../api/v2.0/projects/ID/scanner", "Scanner configure du projet"),
  ],
  "concepts": [
    "Multi-tenant par Projets : RBAC (admin/maintainer/developer/guest), quotas et politiques par projet.",
    "Scan de vulnerabilites integre (Trivy) automatique au push, avec blocage selon severite (CVE policy).",
    "Signature et content trust (Cosign/Notation) + politique d'admission : n'autoriser que des images signees.",
    "Replication declarative entre registres (geo, DR, prod-pull) selon des filtres et un planning.",
    "Retention et immutabilite des tags pour eviter l'ecrasement d'artefacts livres.",
    "Proxy cache (pull-through) de registres publics pour fiabiliser et accelerer les builds CI.",
  ],
  "install": [
    "Deploiement via Harbor Helm chart sur Kubernetes (recommande) ou docker-compose pour PoC.",
    "TLS obligatoire, base externe (Postgres) et stockage objet (S3) pour la production.",
    "Integrer l'authentification entreprise (OIDC/LDAP) et structurer les projets par equipe/environnement.",
    "Configurer le scanner Trivy, les CVE allowlists et les regles d'immutabilite des tags.",
    "Mettre en place les regles de replication (DR/edge) et de retention des le depart.",
  ],
  "cicd": [
    "Le CI pousse l'image ; Harbor la scanne automatiquement et bloque la promotion sur CVE critique.",
    "Promotion par digest entre projets (staging -> prod) via replication ou retag controle.",
    "Cosign sign en CI puis verify a l'admission Kubernetes : chaine de confiance bout en bout.",
    "Proxy cache Harbor comme registre amont des runners CI : builds rapides et resilients aux pannes externes.",
    "Webhooks Harbor declenchant des actions (notification, redeploiement) sur push/scan.",
  ],
  "prod": [
    "Replication geo pour DR et pull local par cluster (latence/resilience).",
    "Retention/quotas evitant la saturation du stockage objet.",
    "Stockage S3 + Postgres externes pour la scalabilite et la sauvegarde.",
    "Disponibilite assuree car critique : tout deploiement depend du registre.",
    "Observabilite (metriques exposees) et alerting sur echecs de scan/replication.",
  ],
  "security": [
    "RBAC par projet au moindre privilege ; robots accounts a portee limitee pour le CI.",
    "Blocage de pull des images vulnerables (CVE policy) et tags immuables.",
    "Signature obligatoire (Cosign) + admission policy cote cluster.",
    "TLS partout, OIDC/LDAP, audit logs — conformite PCI DSS de la supply chain.",
    "Proxy cache reduisant la dependance a des registres publics non maitrises.",
  ],
  "pitfalls": [
    "Stockage local sature : externaliser sur S3 et appliquer retention/quotas.",
    "Tags mutables ecrasant des livraisons : activer l'immutabilite.",
    "Images vulnerables promues car CVE policy non bloquante : durcir la politique.",
    "Robot accounts trop permissifs : restreindre le scope par projet.",
    "Registre non HA : point de defaillance unique des deploiements.",
  ],
  "practices": [
    "Projets RBAC, robots CI a portee minimale.",
    "Scan automatique + CVE policy bloquante + tags immuables.",
    "Signature Cosign + admission policy cote Kubernetes.",
    "Replication DR + retention/quotas + stockage objet externe.",
    "Proxy cache pour des builds CI rapides et resilients.",
  ],
},
}
