# -*- coding: utf-8 -*-
"""Cloud providers."""

TECH = {
"aws": {
  "name": "AWS", "category": "Cloud",
  "role": "Amazon Web Services est le fournisseur cloud leader, offrant 200+ services (calcul EC2/ECS/EKS/Lambda, stockage S3/EBS, reseau VPC, bases RDS/DynamoDB, IAM, observabilite CloudWatch). En DevOps, AWS sert de socle au provisioning automatise (Terraform/CloudFormation), aux clusters Kubernetes manages (EKS) et aux pipelines de livraison, avec un modele de securite IAM granulaire indispensable aux environnements multi-environnements et reglementes.",
  "commands": [
    ("aws configure / aws sts get-caller-identity", "Configurer / verifier l'identite"),
    ("aws s3 sync ./dist s3://bucket --delete", "Synchroniser un bucket"),
    ("aws ec2 describe-instances --filters ...", "Inventaire EC2"),
    ("aws eks update-kubeconfig --name cluster", "Configurer kubectl pour EKS"),
    ("aws ecr get-login-password | docker login ...", "Auth au registre ECR"),
    ("aws logs tail /aws/lambda/fn --follow", "Suivre des logs CloudWatch"),
    ("aws iam simulate-principal-policy ...", "Tester une politique IAM"),
    ("aws ssm start-session --target i-...", "Acces sans bastion (SSM)"),
    ("aws secretsmanager get-secret-value --secret-id s", "Lire un secret"),
    ("aws cloudformation deploy --template-file t", "Deployer une stack"),
    ("aws sts assume-role-with-web-identity ...", "OIDC (CI sans cle statique)"),
    ("aws ce get-cost-and-usage ...", "Analyse de couts"),
  ],
  "concepts": [
    "Modele de responsabilite partagee : AWS securise le cloud, le client securise dans le cloud.",
    "IAM (users/roles/policies, least privilege) + STS (credentials temporaires) = coeur de la securite.",
    "Regions/AZ pour la resilience ; VPC, subnets, SG/NACL pour le reseau et l'isolation.",
    "Calcul : EC2 (VM), ECS/Fargate (conteneurs), EKS (Kubernetes manage), Lambda (serverless).",
    "Stockage S3 (objet, durable) ; RDS/DynamoDB (bases manages) ; KMS (chiffrement).",
    "IaC (Terraform/CloudFormation/CDK) pour des environnements reproductibles.",
  ],
  "install": [
    "Organisation multi-comptes (AWS Organizations) : separation prod/non-prod, SCP, billing consolide.",
    "Acces humain via SSO/Identity Center ; CI via OIDC (pas de cle longue duree).",
    "Tout en IaC (Terraform) avec state distant chiffre/verrouille.",
    "Reseau : VPC par environnement, endpoints prives, pas d'expo publique inutile.",
    "Tags de cout/ownership et budgets/alarmes des le depart.",
  ],
  "cicd": [
    "OIDC GitHub/GitLab -> rôle AWS court-vivant : aucun secret cloud stocke en CI.",
    "Deploy : push ECR -> update EKS/ECS (Helm/kubectl) -> health-check.",
    "Promotion immuable par digest ; environnements isoles par compte.",
    "Secrets via Secrets Manager/SSM injectes au runtime.",
    "Scan IaC (tfsec/Checkov) et cout (Infracost) en pipeline.",
  ],
  "prod": [
    "Multi-AZ par defaut ; Auto Scaling + load balancing pour l'elasticite.",
    "Sauvegardes (RDS snapshots, S3 versioning) et DR testes.",
    "Observabilite CloudWatch + export Prometheus/Grafana ; alarmes SLO.",
    "FinOps : right-sizing, Savings Plans, detection du gaspillage.",
    "Well-Architected reviews (fiabilite, securite, cout, perf).",
  ],
  "security": [
    "IAM least privilege, roles temporaires (STS/OIDC), MFA, pas de cle root.",
    "Chiffrement at rest (KMS) et in transit (TLS) systematique.",
    "GuardDuty/Security Hub/Config pour detection et conformite continue.",
    "Secrets Manager + rotation ; SG/NACL restrictifs, S3 non public.",
    "CloudTrail active partout — audit conforme PCI DSS.",
  ],
  "pitfalls": [
    "Cles IAM longue duree dans le CI : passer a OIDC.",
    "Buckets S3 publics par erreur : Block Public Access global.",
    "Pas de tags de cout : derive budgetaire invisible.",
    "Mono-AZ : indisponibilite sur panne de zone.",
    "Politiques IAM trop larges (*:*).",
  ],
  "practices": [
    "Multi-comptes + SSO + OIDC, least privilege IAM.",
    "Tout en IaC, state chiffre/verrouille.",
    "Chiffrement KMS/TLS, CloudTrail/Config/GuardDuty.",
    "Multi-AZ, autoscaling, sauvegardes/DR testes.",
    "FinOps (tags, budgets, right-sizing).",
  ],
},

"gcp": {
  "name": "Google Cloud (GCP)", "category": "Cloud",
  "role": "Google Cloud Platform fournit calcul (GCE, GKE, Cloud Run), stockage (GCS), reseau, donnees (BigQuery) et un modele IAM hierarchique (Organisation > Dossiers > Projets). GKE est l'un des Kubernetes manages les plus aboutis, et la philosophie SRE de Google irrigue l'outillage (Cloud Operations). GCP est un socle privilegie pour des plateformes data/IA et des deploiements Kubernetes a grande echelle.",
  "commands": [
    ("gcloud auth login / gcloud config set project P", "Auth / projet courant"),
    ("gcloud container clusters get-credentials C --region R", "kubectl pour GKE"),
    ("gcloud builds submit --tag REGION-docker.pkg.dev/P/r/app", "Build + push Artifact Registry"),
    ("gcloud run deploy app --image IMG --region R", "Deployer sur Cloud Run"),
    ("gcloud compute instances list", "Inventaire GCE"),
    ("gcloud iam service-accounts create sa", "Creer un compte de service"),
    ("gcloud secrets versions access latest --secret=s", "Lire un secret"),
    ("gsutil rsync -d ./dist gs://bucket", "Synchroniser GCS"),
    ("gcloud logging read 'severity>=ERROR' --limit 50", "Logs filtres"),
    ("gcloud projects get-iam-policy P", "Politique IAM d'un projet"),
    ("gcloud iam workload-identity-pools create ...", "OIDC (Workload Identity)"),
    ("gcloud billing budgets create ...", "Budget/alerting cout"),
  ],
  "concepts": [
    "Hierarchie IAM : Organisation > Dossiers > Projets ; roles predefinis/custom, least privilege.",
    "GKE (Autopilot/Standard) : Kubernetes manage avec upgrades et scaling automatises.",
    "Cloud Run : conteneurs serverless scalant a zero ; Artifact Registry pour les images.",
    "Workload Identity Federation : CI/charges sans cle de compte de service.",
    "Cloud Operations (Logging/Monitoring/Trace) : observabilite integree d'inspiration SRE.",
    "IaC via Terraform Google provider ; projets comme unite d'isolation.",
  ],
  "install": [
    "Structure Organisation/Dossiers/Projets ; projets separes prod/non-prod.",
    "Workload Identity Federation pour le CI ; SSO pour les humains.",
    "Tout en Terraform, state distant chiffre/verrouille.",
    "VPC partage, Private Google Access, pas d'IP publique inutile.",
    "Budgets/labels de cout et logs centralises des le depart.",
  ],
  "cicd": [
    "Workload Identity Federation -> token court-vivant : pas de cle SA en CI.",
    "Cloud Build/Actions -> Artifact Registry -> deploy GKE/Cloud Run -> health-check.",
    "Promotion immuable par digest ; isolation par projet.",
    "Secrets via Secret Manager injectes au runtime.",
    "Scan IaC + cout en pipeline.",
  ],
  "prod": [
    "GKE multi-zones, node auto-repair/upgrade, autoscaling.",
    "Sauvegardes/DR (snapshots, GCS versioning) testees.",
    "SLO/alerting via Cloud Monitoring + export Prometheus.",
    "FinOps : recommandations, committed use discounts.",
    "Maintenance windows et release channels GKE maitrises.",
  ],
  "security": [
    "IAM hierarchique least privilege, pas de cle SA exportee (WIF).",
    "CMEK/chiffrement par defaut, VPC-SC pour le cloisonnement data.",
    "Security Command Center pour la posture et la conformite.",
    "Secret Manager + rotation ; logs d'audit actives partout.",
    "Private clusters/endpoints — exigences reglementaires.",
  ],
  "pitfalls": [
    "Cles de compte de service exportees : utiliser WIF.",
    "Roles primitifs Owner/Editor trop larges : roles fins.",
    "Buckets GCS publics par erreur.",
    "Clusters publics non restreints.",
    "Absence de labels de cout : derive budgetaire.",
  ],
  "practices": [
    "Hierarchie IAM + projets isoles, WIF pour le CI.",
    "Terraform + state chiffre/verrouille.",
    "Private clusters/endpoints, CMEK, VPC-SC.",
    "GKE autopilot/auto-upgrade, SLO/alerting.",
    "FinOps (labels, budgets, CUD).",
  ],
},

"azure": {
  "name": "Microsoft Azure", "category": "Cloud",
  "role": "Microsoft Azure est le cloud d'entreprise integre a l'ecosysteme Microsoft (Entra ID, AKS, App Service, Azure DevOps). Organisation par Management Groups > Subscriptions > Resource Groups, RBAC Azure et Policy pour la gouvernance. AKS fournit Kubernetes manage et Key Vault la gestion de secrets — un socle courant pour les grands comptes deja investis dans l'ecosysteme Microsoft.",
  "commands": [
    ("az login / az account set -s SUB", "Auth / abonnement courant"),
    ("az aks get-credentials -g RG -n AKS", "kubectl pour AKS"),
    ("az acr build -r REG -t app:tag .", "Build + push ACR"),
    ("az group create -n RG -l westeurope", "Creer un resource group"),
    ("az vm list -d -o table", "Inventaire VM"),
    ("az keyvault secret show --vault-name V -n s", "Lire un secret Key Vault"),
    ("az role assignment create --assignee ID --role R", "Attribuer un role RBAC"),
    ("az monitor activity-log list", "Journal d'activite"),
    ("az deployment group create --template-file t", "Deployer du Bicep/ARM"),
    ("az identity create -g RG -n mi", "Managed Identity"),
    ("az policy assignment create ...", "Gouvernance par policy"),
    ("az consumption usage list", "Analyse de couts"),
  ],
  "concepts": [
    "Hierarchie : Management Groups > Subscriptions > Resource Groups ; RBAC Azure + Azure Policy.",
    "Entra ID (ex-AAD) : identites, Managed Identities (pas de secret pour les charges).",
    "AKS : Kubernetes manage ; ACR pour les images ; Key Vault pour les secrets.",
    "Bicep/ARM/Terraform pour l'IaC ; tags et Policy pour la conformite.",
    "Azure Monitor/Log Analytics : observabilite et alerting integres.",
    "OIDC federation pour le CI sans secret statique.",
  ],
  "install": [
    "Management Groups + subscriptions separees prod/non-prod ; landing zones.",
    "Managed Identities/OIDC plutot que des secrets ; SSO Entra ID.",
    "IaC (Bicep/Terraform) avec state distant chiffre.",
    "VNet, Private Endpoints, pas d'expo publique inutile.",
    "Azure Policy + budgets + tags des le depart.",
  ],
  "cicd": [
    "OIDC -> federated credentials : pipelines sans secret cloud.",
    "Build ACR -> deploy AKS (Helm) -> health-check.",
    "Promotion immuable par digest ; isolation par subscription.",
    "Secrets via Key Vault (CSI driver) au runtime.",
    "Scan IaC + cout en pipeline.",
  ],
  "prod": [
    "AKS multi-zones, node auto-upgrade, cluster autoscaler.",
    "Sauvegardes/DR (snapshots, geo-redundant storage) testees.",
    "Azure Monitor SLO/alerting + export Prometheus.",
    "FinOps : Advisor, reservations, right-sizing.",
    "Maintenance windows AKS maitrisees.",
  ],
  "security": [
    "RBAC Azure least privilege + Managed Identities (zero secret).",
    "Key Vault + rotation ; chiffrement at rest/in transit.",
    "Defender for Cloud pour la posture et la conformite.",
    "Private Endpoints, NSG restrictifs, pas d'IP publique inutile.",
    "Activity/Diagnostic logs — audit conforme.",
  ],
  "pitfalls": [
    "Secrets statiques au lieu de Managed Identity/OIDC.",
    "Owner attribue trop largement : RBAC fin.",
    "Ressources hors landing zone non gouvernees.",
    "Endpoints publics non restreints.",
    "Absence de tags : couts non imputables.",
  ],
  "practices": [
    "Landing zones + subscriptions isolees, RBAC minimal.",
    "Managed Identities/OIDC, Key Vault + rotation.",
    "IaC (Bicep/Terraform) + Policy + budgets.",
    "Private Endpoints, Defender for Cloud.",
    "AKS auto-upgrade, SLO/alerting, FinOps.",
  ],
},

"hetzner": {
  "name": "Hetzner Cloud", "category": "Cloud",
  "role": "Hetzner Cloud est un fournisseur europeen d'infrastructure (serveurs cloud et dedies, volumes, load balancers, reseaux prives) reconnu pour un rapport performance/prix tres competitif. Avec une API simple, un provider Terraform officiel et le cloud-init, il convient parfaitement a l'hebergement maitrise de clusters K3s/Kubernetes, d'environnements de staging et de workloads cout-sensibles, tout en restant data en Europe (RGPD).",
  "commands": [
    ("hcloud context create prod", "Configurer un contexte API"),
    ("hcloud server create --type cx22 --image ubuntu-24.04 --ssh-key k", "Creer un serveur"),
    ("hcloud server list / describe ID", "Inventaire / details"),
    ("hcloud network create --name priv --ip-range 10.0.0.0/16", "Reseau prive"),
    ("hcloud load-balancer create --type lb11", "Load balancer"),
    ("hcloud volume create --size 100 --server ID", "Volume persistant"),
    ("hcloud firewall create / apply-to-resource", "Pare-feu cloud"),
    ("hcloud server create --user-data-from-file ci.yaml", "Bootstrap cloud-init"),
    ("hcloud server enable-rescue ID", "Mode rescue"),
    ("hcloud image list -t snapshot", "Snapshots/images"),
    ("hcloud server reboot/poweroff ID", "Cycle de vie"),
    ("terraform apply (hetznercloud/hcloud)", "IaC officielle"),
  ],
  "concepts": [
    "Ressources : serveurs cloud (CX/CPX), dedies, volumes, reseaux prives, LB, firewalls — API REST simple.",
    "Provider Terraform officiel : infrastructure reproductible as code.",
    "cloud-init pour le provisioning a la creation (handoff vers Ansible).",
    "Reseaux prives + firewalls cloud pour isoler les noeuds (ex. cluster K3s).",
    "Data centers UE (RGPD) ; excellent rapport perf/prix.",
    "Snapshots/images pour la reprise et la replication d'environnements.",
  ],
  "install": [
    "Tout en Terraform (hcloud) ; cles SSH gerees, state distant chiffre.",
    "Reseau prive + firewall des le depart ; pas d'expo publique inutile.",
    "cloud-init minimal puis Ansible pour la configuration complete.",
    "Snapshots planifies et testes (strategie de reprise).",
    "Conventions de labels/contexts par environnement.",
  ],
  "cicd": [
    "Provisioning declaratif Terraform en pipeline (plan/apply gate).",
    "Bootstrap cloud-init + Ansible orchestre par le CI (handoff IaC -> config).",
    "K3s/Kubernetes deploye dessus puis GitOps (Argo/Flux) identique au reste.",
    "Secrets via Vault/CI, jamais en clair dans le user-data.",
    "Tests d'infra (terraform validate/tfsec) avant apply.",
  ],
  "prod": [
    "Load balancer + plusieurs noeuds + reseau prive pour la HA applicative.",
    "Volumes pour la persistance ; snapshots reguliers testes.",
    "Monitoring externe (Prometheus/Grafana) car offre managee limitee.",
    "Sauvegardes applicatives explicites (pas de DBaaS managee complete).",
    "Right-sizing : profiter du cout pour dimensionner correctement.",
  ],
  "security": [
    "Firewalls cloud restrictifs + reseau prive ; SSH par cle uniquement.",
    "Durcissement hote (CIS) car infrastructure plus 'brute' qu'un hyperscaler.",
    "Secrets hors user-data (Vault) ; pas de port de gestion expose.",
    "Mises a jour OS/noyau regulieres (responsabilite client elevee).",
    "Snapshots chiffres/testes pour la reprise.",
  ],
  "pitfalls": [
    "Serveur expose sans firewall cloud/reseau prive.",
    "Pas de monitoring (peu de managed) : angle mort operationnel.",
    "Secrets dans le user-data cloud-init.",
    "Mono-noeud sans LB : indisponibilite sur panne.",
    "Snapshots non testes : reprise illusoire.",
  ],
  "practices": [
    "Terraform officiel + state chiffre, SSH par cle.",
    "Reseau prive + firewall cloud restrictif.",
    "cloud-init -> Ansible, snapshots testes.",
    "Monitoring/sauvegardes explicites (Prometheus/Grafana).",
    "Durcissement hote et MAJ regulieres.",
  ],
},

"ovh": {
  "name": "OVHcloud", "category": "Cloud",
  "role": "OVHcloud est un fournisseur europeen majeur (Public Cloud OpenStack, serveurs dedies/bare metal, Managed Kubernetes, stockage objet S3-compatible). Souverainete des donnees en Europe, bare metal performant et API/Terraform en font une option pertinente pour des workloads cout/souverainete-sensibles, du Kubernetes manage et des architectures hybrides.",
  "commands": [
    ("openstack server list", "Inventaire Public Cloud (OpenStack)"),
    ("openstack server create --flavor f --image i --key-name k s", "Creer une instance"),
    ("openstack network/subnet create ...", "Reseau prive"),
    ("openstack security group rule create ...", "Regles pare-feu"),
    ("kubectl (via kubeconfig Managed Kubernetes)", "Operer le cluster manage"),
    ("aws s3 --endpoint-url https://s3.gra.io.cloud.ovh.net ls", "Stockage objet S3-compatible"),
    ("ovhai (AI Training/Notebooks)", "Charges IA/ML manageees"),
    ("terraform apply (ovh + openstack providers)", "IaC"),
    ("openstack volume create --size 100 v", "Volume Cinder"),
    ("openstack server reboot ID", "Cycle de vie"),
    ("openstack image list", "Images disponibles"),
    ("openstack keypair create k > k.pem", "Cle SSH"),
  ],
  "concepts": [
    "Public Cloud base OpenStack (API standard) ; bare metal performant ; Managed Kubernetes.",
    "Stockage objet S3-compatible ; volumes Cinder pour la persistance.",
    "Souverainete : data centers UE, conformite RGPD, offres certifiees.",
    "IaC via providers Terraform OVH + OpenStack.",
    "Reseaux prives (vRack) pour relier dedies et Public Cloud (hybride).",
    "Managed Kubernetes pour decharger l'operation du control plane.",
  ],
  "install": [
    "Terraform (ovh/openstack) ; cles SSH gerees, state distant chiffre.",
    "Reseau prive (vRack) + security groups restrictifs des le depart.",
    "cloud-init -> Ansible pour la configuration.",
    "Managed Kubernetes + GitOps pour standardiser l'exploitation.",
    "Sauvegardes/snapshots planifies et testes.",
  ],
  "cicd": [
    "Provisioning Terraform en pipeline (plan/apply gate).",
    "Push images vers registre prive/OVH ; deploy Managed Kubernetes (Helm).",
    "Stockage objet S3-compatible pour artefacts/sauvegardes CI.",
    "Secrets via Vault/CI, pas en clair dans le user-data.",
    "tfsec/validate avant apply.",
  ],
  "prod": [
    "Managed Kubernetes multi-noeuds + LB pour la HA.",
    "vRack pour relier bare metal performant et Public Cloud (hybride).",
    "Monitoring/observabilite externes (Prometheus/Grafana/Loki).",
    "Sauvegardes applicatives et snapshots testes.",
    "Right-sizing bare metal vs cloud selon le profil de charge.",
  ],
  "security": [
    "Security groups + vRack ; SSH par cle, pas de port de gestion expose.",
    "Durcissement hote (bare metal = responsabilite client elevee).",
    "Secrets hors user-data (Vault) ; chiffrement objet/volumes.",
    "MAJ OS/noyau regulieres ; conformite RGPD/souverainete.",
    "Snapshots chiffres/testes pour la reprise.",
  ],
  "pitfalls": [
    "Instances exposees sans security group/vRack.",
    "Bare metal non durci/non patche.",
    "Pas de monitoring externe : angle mort.",
    "Secrets dans cloud-init.",
    "Snapshots non testes.",
  ],
  "practices": [
    "Terraform (ovh/openstack) + state chiffre, SSH par cle.",
    "vRack + security groups restrictifs.",
    "Managed Kubernetes + GitOps, cloud-init -> Ansible.",
    "Monitoring/sauvegardes externes, snapshots testes.",
    "Durcissement bare metal, conformite RGPD.",
  ],
},
}
