# -*- coding: utf-8 -*-
"""IaC & gestion de configuration / secrets."""

TECH = {
"terraform": {
  "name": "Terraform", "category": "IaC & Config",
  "role": "Terraform est l'outil d'Infrastructure as Code declaratif de HashiCorp. Il decrit l'infrastructure (reseau, calcul, bases, DNS, IAM) en HCL, calcule un plan de convergence vers l'etat desire et l'applique de maniere idempotente via des providers (AWS, GCP, Azure, Cloudflare...). Le state suit les ressources gerees ; modules et workspaces industrialisent des environnements complets reproductibles en une commande, sur plusieurs clouds — un pilier du provisioning automatise multi-cloud.",
  "commands": [
    ("terraform init -backend-config=...", "Initialiser providers et backend distant"),
    ("terraform fmt -recursive", "Formater le code HCL"),
    ("terraform validate", "Valider la syntaxe et la coherence"),
    ("terraform plan -out=tf.plan", "Calculer et figer le plan"),
    ("terraform apply tf.plan", "Appliquer exactement le plan revu"),
    ("terraform destroy -target=res", "Detruire des ressources ciblees"),
    ("terraform state list / show res", "Inspecter le state"),
    ("terraform state mv A B", "Refactorer sans recreer"),
    ("terraform import res ID", "Importer une ressource existante"),
    ("terraform workspace new staging", "Isoler un environnement"),
    ("terraform output -json", "Exposer des valeurs en sortie"),
    ("terraform taint/untaint res", "Forcer/annuler le remplacement"),
  ],
  "concepts": [
    "Declaratif : on decrit l'etat cible, Terraform calcule le diff (plan) et l'applique (apply) de maniere idempotente.",
    "Le state (local ou backend distant verrouille) est la source de verite des ressources gerees — a proteger absolument.",
    "Les providers traduisent HCL en appels d'API cloud ; les versions sont epinglees pour la reproductibilite.",
    "Les modules encapsulent un pattern reutilisable (VPC, cluster, DB) versionne et parametre par variables.",
    "Le graphe de dependances ordonne creation/destruction ; depends_on gere les liens implicites.",
    "Workspaces/repertoires separent les environnements ; data sources lisent l'existant sans le gerer.",
  ],
  "install": [
    "Installer le binaire (tfenv pour gerer les versions) ; epingler required_version et versions de providers.",
    "Backend distant verrouille obligatoire (S3+DynamoDB / GCS / Terraform Cloud) — jamais de state local partage.",
    "Structurer en modules + couches (network/data/app) et environnements (dev/staging/prod) isoles.",
    "Centraliser les variables sensibles via un secret manager (Vault) injecte au plan/apply, pas en .tfvars committe.",
    "Definir des conventions de ncommage/tags et un module 'commons' pour l'homogeneite.",
  ],
  "cicd": [
    "Pipeline : fmt -> validate -> tflint/tfsec -> plan (artefact) -> revue -> apply gate manuelle en prod.",
    "Le plan est sauvegarde et applique tel quel (terraform apply tf.plan) : ce qui est revu est ce qui est applique.",
    "Verrouillage du state empechant les apply concurrents ; un pipeline = une execution serielle.",
    "Atlantis/Terraform Cloud orchestrent plan/apply par Pull Request avec approbation et audit.",
    "Promotion : meme module versionne, variables par environnement — pas de copier-coller d'infra.",
  ],
  "prod": [
    "State distant chiffre, verrouille et sauvegarde/versionne — sa perte = perte de controle de l'infra.",
    "plan systematique avant apply : aucune modification a l'aveugle en production.",
    "Modules versionnes par tag ; montee de version controlee et testee en staging d'abord.",
    "lifecycle (prevent_destroy, create_before_destroy) protege les ressources critiques (bases, DNS).",
    "Drift detection (plan recurrent) comme controle de conformite continue de l'infrastructure.",
  ],
  "security": [
    "Secrets jamais en clair dans le code/.tfvars committe : Vault/secret manager + variables d'environnement.",
    "State chiffre at rest et acces restreint (il contient des valeurs sensibles en clair).",
    "Scan IaC (tfsec/Checkov) en CI pour bloquer les misconfigurations (SG ouverts, buckets publics).",
    "Credentials cloud court-vivants (OIDC) en CI plutot que des cles statiques.",
    "RBAC sur le backend/Terraform Cloud et separation des roles plan/apply — conformite.",
  ],
  "pitfalls": [
    "State local partage/perdu : adopter un backend distant verrouille des le depart.",
    "apply sans plan revu : changements destructeurs non anticipes.",
    "Secrets dans .tfvars committes : fuite — externaliser via Vault.",
    "Providers/modules non epingles : builds non reproductibles.",
    "Renommer une ressource = destroy/create : utiliser terraform state mv.",
  ],
  "practices": [
    "Backend distant verrouille/chiffre, state sauvegarde.",
    "Modules versionnes, variables par environnement, conventions/tags.",
    "fmt/validate/lint/tfsec/plan en CI, apply en gate revue.",
    "lifecycle de protection sur les ressources critiques.",
    "Drift detection et secrets externalises (Vault).",
  ],
},

"ansible": {
  "name": "Ansible", "category": "IaC & Config",
  "role": "Ansible est l'outil d'automatisation et de gestion de configuration agentless de Red Hat. Via SSH/WinRM et des playbooks YAML idempotents, il configure des serveurs, deploie des applications et orchestre des operations multi-noeuds sans agent a installer. Inventaires statiques/dynamiques, roles reutilisables, Ansible Vault pour les secrets et Galaxy pour le partage en font le standard du provisioning et de l'exploitation reproductible — y compris l'orchestration SSH de fermes de 12+ serveurs.",
  "commands": [
    ("ansible all -i inv -m ping", "Tester la connectivite des hotes"),
    ("ansible-playbook -i inv site.yml", "Executer un playbook"),
    ("ansible-playbook site.yml --check --diff", "Dry-run avec differences"),
    ("ansible-playbook site.yml --limit web --tags deploy", "Cibler hotes/tags"),
    ("ansible-vault encrypt secrets.yml", "Chiffrer un fichier de secrets"),
    ("ansible-playbook site.yml --ask-vault-pass", "Fournir le mot de passe Vault"),
    ("ansible-galaxy install -r requirements.yml", "Installer roles/collections"),
    ("ansible-inventory -i inv --graph", "Visualiser l'inventaire"),
    ("ansible-lint playbooks/", "Linter les playbooks"),
    ("ansible all -m setup", "Collecter les facts d'un hote"),
    ("ansible-playbook ... --start-at-task 'X'", "Reprendre a une tache"),
    ("ansible-playbook ... -e env=prod", "Passer des variables extra"),
  ],
  "concepts": [
    "Agentless : seul SSH (ou WinRM) et Python sur la cible sont requis — deploiement immediat a grande echelle.",
    "Idempotence : un module decrit un etat ; reexecuter un playbook ne change rien si l'etat est deja atteint.",
    "Inventaire (statique/dynamique) + groupes + group_vars/host_vars structurent la flotte et ses variables.",
    "Roles = unite reutilisable (tasks/handlers/templates/defaults) versionnee et partagee via Galaxy.",
    "Handlers declenches par notify pour des actions conditionnelles (redemarrer un service apres conf).",
    "Strategies (linear/free) et serial pilotent l'orchestration (rolling update multi-noeuds).",
  ],
  "install": [
    "pip install ansible / paquet ; configurer ansible.cfg (inventaire, user, become, ssh args).",
    "Structurer le repo : inventories/<env>, group_vars, roles/, playbooks ; requirements.yml pour les deps.",
    "Inventaire dynamique (cloud) pour refleter automatiquement la flotte reelle.",
    "Ansible Vault pour tous les secrets ; mot de passe Vault fourni par le CI de maniere securisee.",
    "Conventions de nommage, roles versionnes (Galaxy) et ansible-lint integre des le depart.",
  ],
  "cicd": [
    "Pipeline : lint -> --syntax-check -> --check --diff (dry-run) -> apply gate sur prod.",
    "Roles versionnes par tag dans requirements.yml : promotion reproductible entre environnements.",
    "serial + rolling pour des deploiements multi-noeuds sans interruption pilotes par le pipeline.",
    "Couple a Terraform : Terraform provisionne, Ansible configure (cloud-init/handoff).",
    "Vault password injecte via secret CI ; aucun secret en clair dans le repo.",
  ],
  "prod": [
    "Rolling updates (serial: N) avec health gates pour fiabiliser les operations multi-serveurs.",
    "Tags et --limit pour des operations chirurgicales (correctif cible) en production.",
    "--check --diff avant tout run reel : pas de changement a l'aveugle.",
    "Idempotence garantissant qu'un re-run remet en conformite sans effets de bord.",
    "AWX/Ansible Automation Platform pour planification, RBAC et audit a l'echelle.",
  ],
  "security": [
    "Tous les secrets via Ansible Vault (ou lookup vers HashiCorp Vault) — jamais en clair.",
    "no_log: true sur les taches sensibles pour eviter la fuite en sortie.",
    "become privilege escalation maitrise ; comptes et cles SSH a portee minimale.",
    "ansible-lint + scan de pratiques (secrets, permissions) en CI.",
    "RBAC et audit via AWX ; durcissement conforme PCI DSS des serveurs cibles.",
  ],
  "pitfalls": [
    "Playbooks non idempotents (command/shell sans creates/when) : preferer les modules.",
    "Secrets en clair dans group_vars : chiffrer avec Vault.",
    "Pas de --check avant prod : changements imprevus.",
    "Inventaire statique obsolete : passer en dynamique.",
    "Roles non versionnes (latest) : promotions non reproductibles.",
  ],
  "practices": [
    "Idempotence stricte (modules, when/creates).",
    "Vault pour tous les secrets, no_log sur les taches sensibles.",
    "Repo structure (inventories/group_vars/roles), roles versionnes.",
    "lint + syntax-check + dry-run en CI, apply en gate.",
    "Rolling updates serial et AWX pour RBAC/audit.",
  ],
},

"pulumi": {
  "name": "Pulumi", "category": "IaC & Config",
  "role": "Pulumi est une plateforme d'Infrastructure as Code qui exprime l'infrastructure dans des langages de programmation generalistes (TypeScript, Python, Go, C#). Au lieu d'un DSL, on beneficie de boucles, conditions, abstractions, tests unitaires et packaging natifs. Pulumi calcule un plan, gere un state (Pulumi Cloud ou backend self-managed) et applique via les memes providers cloud que l'ecosysteme Terraform — ideal pour des abstractions d'infrastructure typees et testables, partagees comme du vrai code.",
  "commands": [
    ("pulumi new aws-typescript", "Initialiser un projet"),
    ("pulumi stack init prod", "Creer un stack (environnement)"),
    ("pulumi config set --secret dbPass ***", "Stocker un secret chiffre"),
    ("pulumi preview --diff", "Plan des changements"),
    ("pulumi up", "Appliquer les changements"),
    ("pulumi destroy", "Detruire le stack"),
    ("pulumi stack output", "Exposer des sorties"),
    ("pulumi stack select staging", "Basculer d'environnement"),
    ("pulumi refresh", "Reconcilier le state avec le reel"),
    ("pulumi stack export > state.json", "Sauvegarder le state"),
    ("pulumi import aws:s3/bucket:Bucket b NAME", "Importer l'existant"),
    ("pulumi about", "Diagnostiquer l'environnement"),
  ],
  "concepts": [
    "IaC en vrai langage : abstractions, boucles, conditions et composants reutilisables typés.",
    "Le state (Pulumi Cloud ou backend S3/Azure/GCS) suit les ressources ; secrets chiffres dans la config.",
    "Stacks = environnements isoles avec leur configuration et leur state propres.",
    "Component Resources encapsulent des patterns d'infra comme des classes reutilisables.",
    "Memes providers que l'ecosysteme cloud ; conversion possible depuis Terraform.",
    "Testabilite : tests unitaires/property sur l'infra avant tout deploiement.",
  ],
  "install": [
    "Installer la CLI + SDK du langage ; choisir un backend de state (Pulumi Cloud ou self-managed chiffre).",
    "Structurer projet + stacks par environnement ; config typee et secrets via pulumi config --secret.",
    "Packager les patterns en Component Resources versionnes (npm/pip/go module).",
    "Epingler versions de providers/SDK pour la reproductibilite.",
    "Integrer tests unitaires d'infra dans la base de code.",
  ],
  "cicd": [
    "Pipeline : install -> lint/test -> pulumi preview (artefact) -> approbation -> pulumi up.",
    "Pulumi GitHub Action/Operator pour des deploiements par PR avec diff visible et audit.",
    "Promotion par stack : meme code, config par environnement — zero duplication.",
    "Secrets chiffres dans la config, dechiffres au déploiement via le provider de secrets.",
    "Tests d'infra executes en CI avant tout up (shift-left infra).",
  ],
  "prod": [
    "preview obligatoire avant up ; verrouillage de state contre les executions concurrentes.",
    "refresh periodique pour detecter et corriger le drift.",
    "Component Resources versionnes : montee de version controlee et testee en staging.",
    "stack export sauvegarde reguliere du state — reprise apres incident.",
    "protect: true sur les ressources critiques pour empecher une destruction accidentelle.",
  ],
  "security": [
    "Secrets chiffres nativement (config --secret) ; providers de secrets (Vault/KMS) integrables.",
    "State chiffre at rest et acces RBAC restreint (il contient des valeurs sensibles).",
    "Scan IaC et tests de policy (Pulumi CrossGuard) bloquant les misconfigurations.",
    "Credentials cloud court-vivants (OIDC) en CI.",
    "Audit des deploiements via Pulumi Cloud — tracabilite conforme.",
  ],
  "pitfalls": [
    "Complexite du code IaC non maitrisee : limiter la logique, factoriser en Components testes.",
    "State non chiffre/non sauvegarde : risque majeur.",
    "up sans preview : changements destructeurs.",
    "Secrets non chiffres dans la config : fuite.",
    "SDK/providers non epingles : non reproductibilite.",
  ],
  "practices": [
    "preview avant up, state chiffre/sauvegarde/verrouille.",
    "Components versionnes et testes unitairement.",
    "Secrets chiffres + provider Vault/KMS.",
    "Policy as code (CrossGuard) en CI.",
    "protect sur les ressources critiques, OIDC pour le cloud.",
  ],
},

"vault": {
  "name": "HashiCorp Vault", "category": "IaC & Config",
  "role": "Vault est le coffre-fort de secrets de HashiCorp. Il centralise stockage, acces et audit des secrets (mots de passe, cles, certificats, tokens) avec chiffrement de bout en bout, politiques fines, et surtout des secrets dynamiques a duree de vie courte (credentials DB/cloud generes a la demande puis revoques). Moteurs PKI, Transit (chiffrement as a service), KV, et integration Kubernetes/CI en font la brique centrale d'une gestion de secrets conforme PCI DSS — zero secret statique en clair.",
  "commands": [
    ("vault server -config=vault.hcl", "Demarrer le serveur"),
    ("vault operator init / unseal", "Initialiser / desceller"),
    ("vault login -method=oidc", "S'authentifier"),
    ("vault kv put secret/app db=*** ", "Ecrire un secret KV"),
    ("vault kv get -field=db secret/app", "Lire un champ"),
    ("vault policy write app app.hcl", "Definir une politique"),
    ("vault read database/creds/app-role", "Generer un credential dynamique"),
    ("vault lease revoke -prefix database/", "Revoquer des leases"),
    ("vault write transit/encrypt/k plaintext=$(base64)", "Chiffrement as a service"),
    ("vault write pki/issue/role common_name=app", "Emettre un certificat court"),
    ("vault audit enable file file_path=/var/log/vault.log", "Activer l'audit"),
    ("vault token create -policy=app -ttl=1h", "Creer un token a TTL"),
  ],
  "concepts": [
    "Secrets statiques (KV) mais surtout dynamiques : credentials generes a la demande, TTL court, revocation automatique.",
    "Auth methods (Kubernetes, OIDC, AppRole, JWT) + policies HCL = controle d'acces fin et identitaire.",
    "Seal/unseal : Vault demarre scelle ; auto-unseal via KMS cloud en production.",
    "Moteurs : KV, Database, PKI (CA interne), Transit (chiffrement sans exposer la cle), Cloud (AWS/GCP).",
    "Leases et renouvellement : chaque secret a une duree de vie tracee et revocable instantanement.",
    "Audit devices : tout acces est journalise de maniere infalsifiable — exigence reglementaire.",
  ],
  "install": [
    "Deploiement HA (Raft integre ou Consul) avec auto-unseal KMS et TLS obligatoire.",
    "Structurer mounts/policies par equipe/application ; principe du moindre privilege.",
    "Integrer l'auth Kubernetes (ServiceAccount -> role) et OIDC pour les humains.",
    "Activer les audit devices des l'initialisation ; sauvegarde reguliere du storage Raft.",
    "Automatiser la configuration (Terraform Vault provider) pour une conf reproductible et auditable.",
  ],
  "cicd": [
    "Le pipeline s'authentifie (JWT/OIDC/AppRole) et recupere des secrets court-vivants au runtime.",
    "Aucun secret statique stocke dans le CI : credentials DB/cloud dynamiques generes par job puis revoques.",
    "Vault Agent / sidecar injecte les secrets dans les conteneurs sans les ecrire sur disque.",
    "Transit pour signer/chiffrer des artefacts sans jamais exposer la cle au pipeline.",
    "Terraform Vault provider pour gerer policies/roles as code, revus en PR.",
  ],
  "prod": [
    "HA + auto-unseal + sauvegardes Raft testees : Vault est critique, son indisponibilite bloque tout.",
    "Secrets dynamiques a TTL court : reduction drastique de la surface en cas de fuite.",
    "Rotation automatique des credentials/certificats (PKI courte duree).",
    "Observabilite (telemetry Prometheus) et alerting sur seal/leases/erreurs.",
    "Plan de reprise documente (unseal keys/Shamir, DR replication).",
  ],
  "security": [
    "Zero secret en clair : KV chiffre + dynamiques + Transit ; rien sur disque cote application.",
    "Policies au moindre privilege, auth identitaire (K8s/OIDC), tokens a TTL court.",
    "Audit infalsifiable de tous les acces — tracabilite PCI DSS complete.",
    "Auto-unseal KMS, TLS mutuel, root token revoque apres bootstrap.",
    "Revocation immediate (lease revoke) en cas de compromission.",
  ],
  "pitfalls": [
    "Root token conserve : le revoquer apres configuration initiale.",
    "Pas d'auto-unseal : indisponibilite a chaque redemarrage.",
    "Secrets statiques longue duree au lieu de dynamiques : surface elevee.",
    "Policies trop larges : violation du moindre privilege.",
    "Storage Raft non sauvegarde : perte irreversible des secrets.",
  ],
  "practices": [
    "Secrets dynamiques + TTL courts par defaut.",
    "Auth identitaire (K8s/OIDC), policies minimales, root token revoque.",
    "HA + auto-unseal KMS + sauvegardes Raft testees.",
    "Audit devices actives, rotation automatique (PKI/Transit).",
    "Configuration as code (Terraform) et alerting.",
  ],
},
}
