# -*- coding: utf-8 -*-
"""Langages & scripting."""

TECH = {
"python": {
  "name": "Python", "category": "Langages / Scripting",
  "role": "Python est un langage interprete polyvalent, lisible et a typage dynamique, omnipresent en DevOps, automatisation, data et IA. Sa bibliotheque standard riche, son ecosysteme (requests, boto3, paramiko, pytest, FastAPI) et ses environnements virtuels en font l'outil ideal pour l'orchestration multi-serveurs, l'outillage CI, l'analyse transactionnelle et le glue code d'integration. Sa courbe d'apprentissage douce et sa portabilite expliquent son adoption massive pour fiabiliser les operations.",
  "commands": [
    ("python -m venv .venv && source .venv/bin/activate", "Environnement virtuel isole"),
    ("pip install -r requirements.txt", "Installer les dependances epinglees"),
    ("pip freeze > requirements.txt", "Figer les versions"),
    ("python -m pytest -q --cov", "Tests + couverture"),
    ("python -m black . && ruff check .", "Format + lint"),
    ("python -m mypy src/", "Verification de types statique"),
    ("python -m pip install pipx && pipx install poetry", "Gestion d'outils/projets"),
    ("python -m http.server 8000", "Serveur statique de debug"),
    ("python -c 'import sys; print(sys.version)'", "Inspecter l'interpreteur"),
    ("python -m json.tool < f.json", "Formater/valider du JSON"),
    ("PYTHONPATH=src python -m app", "Lancer un module"),
    ("python -m cProfile -s tottime s.py", "Profiler un script"),
  ],
  "concepts": [
    "Typage dynamique fort ; les annotations de type (PEP 484) + mypy apportent une securite statique optionnelle.",
    "Environnements virtuels (venv/poetry) isolent les dependances par projet — reproductibilite.",
    "Le GIL serialise le bytecode : I/O-bound -> threads/asyncio ; CPU-bound -> multiprocessing.",
    "Tout est objet ; gestionnaires de contexte (with) et generateurs gerent ressources et flux memoire.",
    "Ecosysteme DevOps : boto3 (AWS), paramiko/fabric (SSH), requests, click/argparse (CLI), pytest.",
    "Packaging via pyproject.toml ; entry points pour des CLI distribuables.",
  ],
  "install": [
    "Utiliser pyenv pour gerer les versions ; un venv par projet, dependances epinglees (lockfile).",
    "Structurer src/ + tests/ + pyproject.toml ; pre-commit (black/ruff/mypy) des le depart.",
    "Eviter le Python systeme ; conteneuriser pour les outils livres en CI.",
    "Definir des extras/optionnels pour separer runtime et outillage de dev.",
    "Pinner les versions transitive (pip-tools/poetry.lock) pour des builds deterministes.",
  ],
  "cicd": [
    "Pipeline : install (cache pip) -> ruff/black --check -> mypy -> pytest --cov -> build -> publish.",
    "Matrice de versions Python pour valider la compatibilite.",
    "Outils internes d'orchestration SSH/cloud (paramiko/boto3) packages et testes comme du vrai code.",
    "Cache du repertoire pip/poetry pour accelerer les jobs.",
    "Scan dependances (pip-audit/safety) integre au pipeline.",
  ],
  "prod": [
    "Conteneuriser avec une base mince et un venv ; processus stateless.",
    "Gestion explicite des erreurs/timeouts/retries pour les scripts d'exploitation multi-serveurs.",
    "Logging structure (JSON) plutot que print, niveaux et correlation.",
    "asyncio pour l'I/O massif (orchestration de centaines d'hotes).",
    "Profilage (cProfile) et optimisation ciblee des points chauds.",
  ],
  "security": [
    "pip-audit/safety pour les CVE de dependances ; epingler par hash.",
    "Jamais de secret en dur : variables d'environnement / Vault.",
    "Eviter eval/exec/pickle sur donnees non fiables ; valider les entrees.",
    "Bandit (SAST Python) en CI pour detecter les patterns dangereux.",
    "Sous-processus sans shell=True sur entrees non maitrisees.",
  ],
  "pitfalls": [
    "Dependances non epinglees : builds non reproductibles.",
    "Etat global mutable / arguments par defaut mutables : bugs subtils.",
    "Bloquer l'event loop async avec du CPU-bound.",
    "Exceptions avalees (except: pass) masquant les erreurs.",
    "Python systeme pollue : toujours un venv.",
  ],
  "practices": [
    "venv + lockfile, pre-commit (black/ruff/mypy).",
    "Annotations de type + mypy, tests pytest + couverture.",
    "Logging structure, gestion explicite erreurs/retries.",
    "Scan secrets/dependances (bandit/pip-audit).",
    "Code d'outillage traite comme du code de production (tests, revue).",
  ],
},

"go": {
  "name": "Go", "category": "Langages / Scripting",
  "role": "Go (Golang) est un langage compile, statiquement type, concu pour la simplicite, la performance et la concurrence. Compilation en binaire statique unique sans dependances, demarrage instantane, faible empreinte memoire et goroutines/channels pour la concurrence massive en font le langage de predilection des outils d'infrastructure (Docker, Kubernetes, Terraform) et du traitement haute performance — ideal pour developper des outils internes rapides et portables.",
  "commands": [
    ("go mod init module && go mod tidy", "Initialiser/nettoyer les dependances"),
    ("go build -o bin/app ./...", "Compiler en binaire"),
    ("CGO_ENABLED=0 go build -ldflags '-s -w'", "Binaire statique minimal"),
    ("go test ./... -race -cover", "Tests + detecteur de courses"),
    ("go vet ./... && golangci-lint run", "Analyse statique + lint"),
    ("go run ./cmd/app", "Executer sans builder"),
    ("go fmt ./...", "Formater le code"),
    ("GOOS=linux GOARCH=arm64 go build", "Cross-compilation"),
    ("go tool pprof cpu.prof", "Profilage CPU/memoire"),
    ("go install pkg@v1.2.3", "Installer un outil epingle"),
    ("go test -bench=. -benchmem", "Benchmarks"),
    ("go mod verify", "Verifier l'integrite des modules"),
  ],
  "concepts": [
    "Compilation en binaire statique unique : deploiement trivial (copier le binaire), images conteneur minimales.",
    "Concurrence native : goroutines legeres + channels (CSP) ; context pour annulation/timeouts.",
    "Typage statique strict, gestion d'erreurs explicite (valeurs d'erreur) — code robuste et previsible.",
    "Modules (go.mod/go.sum) : dependances epinglees et verifiees par hash.",
    "GC a faible latence ; -race detecte les courses de donnees a la compilation des tests.",
    "Bibliotheque standard riche (net/http, encoding, os/exec) — peu de dependances tierces.",
  ],
  "install": [
    "Installer la toolchain Go ; un module par projet, versions epinglees, go.sum committe.",
    "Structurer cmd/ + internal/ + pkg/ ; golangci-lint + gofmt en pre-commit.",
    "Build statique (CGO_ENABLED=0) pour des images distroless/scratch.",
    "Vendoring optionnel pour des builds hermetiques.",
    "Makefile/Taskfile pour standardiser build/test/lint.",
  ],
  "cicd": [
    "Pipeline rapide : go vet -> golangci-lint -> go test -race -cover -> build multi-arch -> image scratch.",
    "Cross-compilation (GOOS/GOARCH) pour livrer des binaires multi-plateformes en un job.",
    "Cache du module cache Go pour accelerer les builds.",
    "Outils internes (orchestration, parseurs haute perf) livres comme binaires testes et versionnes.",
    "Scan (govulncheck) integre au pipeline.",
  ],
  "prod": [
    "Binaire statique + image scratch : surface minimale, demarrage instantane, faible RAM.",
    "context partout pour timeouts/annulation — robustesse des services I/O.",
    "pprof expose pour profiler en production sans redeployer.",
    "Concurrence maitrisee (worker pools bornes) pour le traitement haut debit.",
    "GOMAXPROCS/limits coherents avec les cgroups conteneur.",
  ],
  "security": [
    "govulncheck pour les CVE ; go.sum garantit l'integrite des dependances.",
    "Image scratch/distroless non-root : surface d'attaque quasi nulle.",
    "Pas de secret en dur ; validation stricte des entrees.",
    "os/exec sans shell ; eviter l'injection de commandes.",
    "Builds reproductibles (-trimpath, modules verifies).",
  ],
  "pitfalls": [
    "Goroutines fuyantes sans context/cancel : fuite memoire.",
    "Erreurs ignorees (_ =) masquant des defaillances.",
    "Courses de donnees non detectees : toujours go test -race.",
    "Sur-ingenierie d'abstractions : Go privilegie la simplicite.",
    "CGO active cassant le binaire statique sans necessite.",
  ],
  "practices": [
    "Binaire statique, image scratch non-root.",
    "context pour timeouts/annulation, erreurs explicites.",
    "go test -race -cover, golangci-lint, govulncheck en CI.",
    "Modules epingles/verifies, builds reproductibles.",
    "Concurrence bornee (worker pools), pprof en prod.",
  ],
},

"bash": {
  "name": "Bash", "category": "Langages / Scripting",
  "role": "Bash est le shell et langage de script Unix omnipresent, colle universel de l'automatisation : provisioning, glue de pipelines CI, orchestration d'operations serveur et taches d'exploitation. Sa disponibilite par defaut sur quasiment tout systeme Linux en fait l'outil incontournable pour scripter rapidement, a condition d'appliquer une discipline stricte (mode strict, quoting, shellcheck) pour des scripts robustes et previsibles.",
  "commands": [
    ("set -euo pipefail", "Mode strict (echec rapide, vars non definies)"),
    ("trap 'cleanup' EXIT INT TERM", "Nettoyage garanti en sortie"),
    ("shellcheck script.sh", "Linter statique des scripts"),
    ("bash -n script.sh", "Verifier la syntaxe sans executer"),
    ("\"${VAR:?message}\"", "Echouer si variable manquante"),
    ("mapfile -t arr < <(cmd)", "Lire des lignes dans un tableau"),
    ("while IFS= read -r l; do ...; done < f", "Iterer ligne par ligne sans surprise"),
    ("cmd1 | cmd2 || exit 1", "Chaine avec gestion d'erreur"),
    ("[[ -n \"$x\" ]] && do_x", "Test conditionnel sur"),
    ("printf '%s\\n' \"$msg\"", "Sortie sure (vs echo)"),
    ("getopts 'f:v' opt", "Parser des options"),
    ("timeout 30 cmd", "Borner la duree d'une commande"),
  ],
  "concepts": [
    "Le mode strict (set -euo pipefail) transforme les erreurs silencieuses en echecs immediats — indispensable.",
    "Le quoting (\"$var\") evite le word-splitting/glob : source n1 des bugs shell.",
    "trap garantit le nettoyage (fichiers temporaires, verrous) meme en cas d'erreur/signal.",
    "Codes de retour et pipefail : controler l'echec de chaque maillon d'un pipe.",
    "Tableaux et [[ ]] (vs [ ]) pour des tests robustes ; printf plutot qu'echo.",
    "Idempotence : verifier l'etat avant d'agir (existence, deja applique).",
  ],
  "install": [
    "Bash present par defaut ; epingler #!/usr/bin/env bash et viser bash 4+ pour mapfile/associatifs.",
    "Integrer shellcheck en pre-commit/CI ; structurer en fonctions + main().",
    "Variables en lecture seule pour les constantes, locales dans les fonctions.",
    "Fichiers de conf source-es avec validation ; pas de logique metier lourde (passer a Python au-dela).",
    "Conventions : noms explicites, usage()/help, codes de sortie documentes.",
  ],
  "cicd": [
    "Glue de pipelines : wrappers de build/deploy robustes avec set -euo pipefail + trap.",
    "shellcheck obligatoire en CI : echec sur warning pour des scripts fiables.",
    "Scripts idempotents reutilisables entre environnements (parametres, pas de hardcode).",
    "timeout autour des commandes reseau pour eviter les pipelines bloques.",
    "Sortie structuree/journaux clairs pour le diagnostic des jobs.",
  ],
  "prod": [
    "Idempotence et verifications prealables : un re-run ne casse rien.",
    "trap de nettoyage et verrous (flock) pour eviter les executions concurrentes.",
    "timeout + retries bornes pour les operations reseau multi-serveurs.",
    "Journalisation horodatee et codes de sortie explicites pour l'exploitation.",
    "Limiter la complexite : au-dela d'un seuil, reecrire en Python/Go.",
  ],
  "security": [
    "Quoting systematique ; jamais d'eval sur entree non fiable.",
    "Pas de secret en dur ni en argument (visible dans ps) : variables d'env/Vault.",
    "Valider/normaliser les entrees ; chemins absolus, IFS maitrise.",
    "shellcheck detecte injections et patterns dangereux.",
    "Permissions strictes (umask) sur fichiers temporaires sensibles.",
  ],
  "pitfalls": [
    "Variables non quotees : word-splitting et glob inattendus.",
    "Absence de set -euo pipefail : erreurs silencieuses.",
    "Parser ls/echo : utiliser globbing/printf et read.",
    "Secrets en arguments visibles via ps.",
    "Scripts trop longs : migrer vers un vrai langage.",
  ],
  "practices": [
    "set -euo pipefail + trap + shellcheck systematiques.",
    "Quoting strict, printf, [[ ]], fonctions + main().",
    "Idempotence, timeout, flock, retries bornes.",
    "Secrets via env/Vault, validation des entrees.",
    "Seuil de complexite : basculer vers Python/Go.",
  ],
},

"powershell": {
  "name": "PowerShell", "category": "Langages / Scripting",
  "role": "PowerShell est le shell et langage d'automatisation oriente objet de Microsoft, multiplateforme depuis PowerShell 7 (Core). Contrairement aux shells texte, le pipeline transporte des objets .NET typés, ce qui rend le traitement de donnees, l'administration Windows/Active Directory, l'automatisation cloud (Az/AWS.Tools) et les workflows multi-OS particulierement robustes et expressifs — un atout pour les environnements de test et l'exploitation heterogene.",
  "commands": [
    ("$ErrorActionPreference='Stop'", "Echec rapide sur erreur"),
    ("Set-StrictMode -Version Latest", "Detecter variables/usages invalides"),
    ("Get-Help cmdlet -Full", "Documentation d'une cmdlet"),
    ("Get-Command -Module Az", "Lister les cmdlets d'un module"),
    ("Invoke-Pester -CI", "Tests unitaires Pester"),
    ("Invoke-ScriptAnalyzer -Path .", "Lint statique (PSScriptAnalyzer)"),
    ("$obj | ConvertTo-Json -Depth 10", "Serialiser un objet"),
    ("Get-Process | Where-Object CPU -gt 100", "Pipeline objet filtre"),
    ("try { } catch { } finally { }", "Gestion d'erreurs structuree"),
    ("Install-Module Az -Scope CurrentUser", "Installer un module"),
    ("Invoke-Command -ComputerName n -ScriptBlock {}", "Execution distante (remoting)"),
    ("Start-Transcript -Path log.txt", "Journaliser une session"),
  ],
  "concepts": [
    "Pipeline d'objets .NET typés : pas de parsing de texte fragile — proprietes/methodes directement accessibles.",
    "Cmdlets Verbe-Nom coherentes et decouvrables (Get-Help/Get-Command).",
    "$ErrorActionPreference='Stop' + try/catch = gestion d'erreurs deterministe (sinon erreurs non bloquantes).",
    "Modules (PowerShell Gallery) pour cloud (Az, AWS.Tools), AD, etc. ; fonctions avancees ([CmdletBinding()]).",
    "Remoting (WinRM/SSH) pour l'orchestration multi-machines, y compris cross-OS avec PS7.",
    "Pester pour les tests, PSScriptAnalyzer pour le lint — qualite as code.",
  ],
  "install": [
    "PowerShell 7+ (multiplateforme) ; #requires -Version 7 et modules epingles via PSResourceGet.",
    "Set-StrictMode + $ErrorActionPreference='Stop' en tete de tout script.",
    "Structurer en modules/fonctions avancees ; PSScriptAnalyzer + Pester en pre-commit.",
    "Eviter Windows PowerShell 5.1 pour le nouveau code (limites, fin de vie fonctionnelle).",
    "Conventions de verbes approuves (Get-Verb) et comment-based help.",
  ],
  "cicd": [
    "Pipeline : Invoke-ScriptAnalyzer -> Invoke-Pester -CI -> packaging module -> publication.",
    "Scripts d'automatisation multi-OS (PS7) reutilises entre environnements de test.",
    "Az/AWS modules pour l'automatisation cloud pilotee par le pipeline.",
    "Sortie objet -> JSON pour chainer avec d'autres etapes/outils.",
    "Echec du job sur warning d'analyzer pour garantir la qualite.",
  ],
  "prod": [
    "Idempotence et verifications prealables ; -WhatIf/-Confirm sur operations destructrices.",
    "Remoting securise (SSH/WinRM HTTPS) pour l'exploitation multi-noeuds.",
    "Journalisation (Start-Transcript / logs structures) pour l'audit operationnel.",
    "Gestion d'erreurs structuree + codes de sortie pour l'integration pipeline.",
    "Modules versionnes : promotions reproductibles.",
  ],
  "security": [
    "Execution policy + scripts signes en environnement Windows verrouille.",
    "Pas de secret en clair : SecretManagement/Vault, jamais en argument.",
    "Eviter Invoke-Expression sur entree non fiable (injection).",
    "PSScriptAnalyzer detecte les patterns dangereux ; remoting chiffre.",
    "Moindre privilege pour les comptes d'execution (JEA possible).",
  ],
  "pitfalls": [
    "Erreurs non bloquantes par defaut : definir ErrorActionPreference='Stop'.",
    "Cibler 5.1 pour du nouveau code multiplateforme.",
    "Invoke-Expression sur input externe : injection.",
    "Verbes non approuves nuisant a la decouvrabilite.",
    "Secrets passes en arguments visibles.",
  ],
  "practices": [
    "PS7+, StrictMode + ErrorAction Stop + try/catch.",
    "Fonctions avancees, verbes approuves, comment-based help.",
    "Pester + PSScriptAnalyzer en CI.",
    "SecretManagement/Vault, remoting chiffre, moindre privilege.",
    "-WhatIf/-Confirm sur operations destructrices, modules versionnes.",
  ],
},

"groovy": {
  "name": "Groovy (Jenkins)", "category": "Langages / Scripting",
  "role": "Groovy est le langage dynamique de la JVM qui motorise les pipelines Jenkins (Jenkinsfile, declaratif et scripte) et les Shared Libraries. Sa syntaxe concise, son interoperabilite Java et ses closures permettent de factoriser la logique CI/CD a l'echelle d'une organisation : etapes standardisees, scan securite, deploiement Helm, gates d'approbation — reutilisees par des centaines de pipelines de maniere testable et versionnee.",
  "commands": [
    ("pipeline { agent any; stages { } }", "Pipeline declaratif"),
    ("node('linux') { stage('Build') { } }", "Pipeline scripte"),
    ("library 'shared@v1.4.0'", "Charger une Shared Library versionnee"),
    ("def v = sh(returnStdout:true, script:'git rev-parse HEAD').trim()", "Capturer une sortie shell"),
    ("withCredentials([string(credentialsId:'t', variable:'TOK')]) { }", "Injecter un secret"),
    ("parallel(a:{...}, b:{...})", "Branches paralleles"),
    ("retry(3) { sh './flaky.sh' }", "Reessayer une etape"),
    ("timeout(time:15, unit:'MINUTES') { }", "Borner une etape"),
    ("input message:'Deploy?', submitter:'rel'", "Gate d'approbation"),
    ("error 'message'", "Echouer explicitement"),
    ("readJSON / writeYaml (pipeline-utility-steps)", "Manipuler des donnees"),
    ("@Library('shared') _", "Import implicite d'une lib"),
  ],
  "concepts": [
    "Declaratif (structure, lisible, contraint) vs scripte (Groovy complet pour la logique avancee).",
    "Shared Libraries : vars/ (steps globaux) + src/ (classes) versionnees et reutilisees a l'echelle.",
    "Closures et map d'arguments nommes pour des steps configurables et expressifs.",
    "Sandbox + script approval encadrent l'execution de Groovy non fiable (securite).",
    "Interop Java : acces a tout l'ecosysteme JVM depuis le pipeline.",
    "CPS (Continuation Passing Style) : certaines constructions non serialisables -> @NonCPS.",
  ],
  "install": [
    "Pas d'installation : Groovy s'execute dans Jenkins ; structurer une Shared Library (vars/src/test).",
    "Versionner la lib par tag ; jamais @main en production (reproductibilite).",
    "Activer la sandbox et la politique d'approbation de scripts.",
    "Conventions : steps idempotents, parametres nommes, documentation des vars.",
    "JenkinsPipelineUnit pour tester la lib unitairement.",
  ],
  "cicd": [
    "Factoriser build/scan/deploy en steps de Shared Library appeles par tous les Jenkinsfile.",
    "Pipeline declaratif minimal cote projet, logique dans la lib testee/versionnee.",
    "parallel/retry/timeout pour des pipelines rapides et resilients.",
    "Gates input avec submitter pour la conformite des deploiements prod.",
    "Lib promue par tag : un changement de logique CI est revu et versionne.",
  ],
  "prod": [
    "Steps idempotents et rollback-friendly reutilises sur des centaines de pipelines.",
    "timeout/retry pour eviter les pipelines bloques saturant les agents.",
    "Lib versionnee par tag : pas d'effet de bord global non maitrise.",
    "Observabilite : duree/echec exposes comme KPI.",
    "Tests de la lib (JenkinsPipelineUnit) avant promotion.",
  ],
  "security": [
    "Sandbox + script approval pour empecher l'execution de code arbitraire.",
    "Secrets via withCredentials (masques) ; jamais en clair dans le Groovy.",
    "Lib de confiance versionnee ; revue de code obligatoire des steps.",
    "Isolation des pipelines non fiables (forks) sans acces aux secrets prod.",
    "@NonCPS prudent (peut contourner la sandbox).",
  ],
  "pitfalls": [
    "Pipeline scripte monolithique : factoriser en Shared Library.",
    "@main en prod : non reproductible — taguer la lib.",
    "Erreurs CPS/serialisation : isoler en @NonCPS quand justifie.",
    "Secrets en clair dans le Jenkinsfile : utiliser withCredentials.",
    "Lib non testee cassant des centaines de pipelines.",
  ],
  "practices": [
    "Declaratif cote projet + Shared Library testee/versionnee.",
    "Steps idempotents, parametres nommes, documentes.",
    "Sandbox/approval actives, secrets via withCredentials.",
    "parallel/retry/timeout pour resilience et vitesse.",
    "JenkinsPipelineUnit + revue de code de la lib.",
  ],
},

"typescript": {
  "name": "TypeScript", "category": "Langages / Scripting",
  "role": "TypeScript est un sur-ensemble type de JavaScript qui compile vers du JS standard. Le typage statique structurel detecte les erreurs a la compilation, ameliore la maintenabilite et l'outillage (autocompletion, refactoring sur), et s'impose pour les frontends modernes (React/Next.js), les backends Node (NestJS) et l'outillage IaC (CDK/Pulumi). Generics, types utilitaires et strict mode permettent des bases de code larges, sures et evolutives.",
  "commands": [
    ("npm ci", "Installer exactement le lockfile"),
    ("npx tsc --noEmit", "Verifier les types sans generer"),
    ("npx tsc -p tsconfig.json", "Compiler le projet"),
    ("npx eslint . --max-warnings=0", "Lint strict"),
    ("npx prettier --check .", "Verifier le formatage"),
    ("npm test -- --coverage", "Tests + couverture"),
    ("npx tsx script.ts", "Executer un script TS directement"),
    ("npm run build", "Build applicatif (Next/Nest)"),
    ("npm audit --production", "Audit des dependances"),
    ("npx depcheck", "Detecter deps inutilisees"),
    ("tsc --build --watch", "Build incremental en watch"),
    ("npm outdated", "Lister les deps obsoletes"),
  ],
  "concepts": [
    "Typage structurel a la compilation ; strict mode (strictNullChecks, noImplicitAny) maximise la securite.",
    "Types avances : generics, unions/intersections, types utilitaires, narrowing, discriminated unions.",
    "Compilation/transpile vers JS cible ; les types disparaissent a l'execution (effacement).",
    "Ecosysteme : Next.js (front SSR), NestJS (back), AWS CDK/Pulumi (IaC typee).",
    "tsconfig pilote cible, modules, strictness ; les @types fournissent les definitions des libs JS.",
    "Outillage superieur : autocompletion, refactor sur, detection precoce des regressions.",
  ],
  "install": [
    "Node LTS + npm ci (lockfile) ; tsconfig strict des le depart.",
    "ESLint + Prettier + typescript-eslint en pre-commit/CI.",
    "Structurer src/ + tests ; chemins d'alias propres (paths).",
    "Epingler les versions ; @types coherents avec les libs.",
    "Build reproductible (CI) et conteneurise pour livraison.",
  ],
  "cicd": [
    "Pipeline : npm ci -> tsc --noEmit -> eslint --max-warnings=0 -> test --coverage -> build -> image.",
    "Type-check comme gate de qualite bloquante (zero any implicite).",
    "Cache node_modules/build pour des jobs rapides.",
    "Outillage IaC TS (CDK/Pulumi) teste comme du code applicatif.",
    "npm audit/Snyk integre au pipeline.",
  ],
  "prod": [
    "Build optimise (tree-shaking, splitting) ; sourcemaps pour le diagnostic.",
    "Strictness elevee = moins de bugs runtime en production.",
    "Images conteneur multi-stage (build TS -> runtime JS minimal).",
    "Observabilite : logs structures, types partages front/back (contrats surs).",
    "Mises a jour de deps maitrisees (renovate) et testees.",
  ],
  "security": [
    "npm audit/Snyk pour les CVE ; lockfile committe et verifie.",
    "Pas de secret dans le bundle front ; variables d'environnement cote serveur.",
    "Validation runtime des entrees (zod) : les types n'existent pas a l'execution.",
    "Eviter any/as non maitrises qui contournent la securite de types.",
    "Builds reproductibles et dependances epinglees (supply chain).",
  ],
  "pitfalls": [
    "Abus de any/as : perte du benefice du typage.",
    "Confondre types compile-time et validation runtime (zod requis).",
    "tsconfig non strict laissant passer des bugs.",
    "Deps non epinglees / lockfile absent.",
    "Secrets exposes dans le bundle client.",
  ],
  "practices": [
    "tsconfig strict, zero any implicite.",
    "ESLint/Prettier + tsc --noEmit en CI bloquants.",
    "Validation runtime (zod) en complement des types.",
    "npm ci + lockfile, deps epinglees, audit.",
    "Build multi-stage, logs structures, contrats types partages.",
  ],
},

"java": {
  "name": "Java", "category": "Langages / Scripting",
  "role": "Java est un langage objet, statiquement type, compile en bytecode portable execute par la JVM. Robustesse, ecosysteme mature (Spring Boot, Maven/Gradle) et outillage industriel en font le socle de nombreuses applications d'entreprise et bancaires. La maitrise du build (Maven/Gradle), du packaging conteneur et du tuning JVM est centrale pour industrialiser des pipelines CI/CD de microservices Spring Boot deployes sur Kubernetes.",
  "commands": [
    ("mvn -B clean package", "Build + tests + packaging"),
    ("mvn -B verify -Pintegration", "Tests d'integration (profil)"),
    ("mvn dependency:tree", "Arbre des dependances"),
    ("mvn versions:display-dependency-updates", "Mises a jour disponibles"),
    ("./gradlew build --scan", "Build Gradle + analyse"),
    ("./gradlew test jacocoTestReport", "Tests + couverture"),
    ("java -jar app.jar --spring.profiles.active=prod", "Lancer un Spring Boot"),
    ("java -XX:+UseG1GC -Xms512m -Xmx512m -jar app.jar", "Tuning JVM"),
    ("jcmd PID Thread.print", "Diagnostic threads"),
    ("jstack / jmap -heap PID", "Diagnostic JVM"),
    ("mvn org.owasp:dependency-check:check", "Scan vulnerabilites deps"),
    ("jib build (plugin)", "Image conteneur sans Dockerfile"),
  ],
  "concepts": [
    "Compilation en bytecode portable ; la JVM JIT-compile a chaud pour de hautes performances.",
    "Maven/Gradle gerent dependances, build reproductible, profils et lifecycle de tests.",
    "Spring Boot : autoconfiguration, actuator (health/metrics), packaging fat-jar.",
    "GC (G1/ZGC) et heap a dimensionner ; -XX:+UseContainerSupport respecte les cgroups.",
    "Tests : JUnit5/Mockito (unit), Testcontainers (integration realiste).",
    "Observabilite : Micrometer -> Prometheus, actuator endpoints.",
  ],
  "install": [
    "JDK LTS (17/21) gere par sdkman ; build via Maven/Gradle wrapper committe.",
    "Profils Maven par environnement ; dependances epinglees (BOM Spring).",
    "Dockerfile multi-stage ou Jib pour des images reproductibles minimales.",
    "Spring Boot Actuator active (health/readiness) pour Kubernetes.",
    "JaCoCo + SpotBugs/SonarQube integres des le depart.",
  ],
  "cicd": [
    "Pipeline : mvn verify -> JaCoCo -> SonarQube quality gate -> build image (Jib) -> scan -> deploy Helm.",
    "Cache du repository Maven/Gradle pour accelerer les jobs.",
    "Profils -P pour separer unit/integration ; Testcontainers en CI.",
    "Promotion immuable par digest d'image ; rollback Helm.",
    "OWASP dependency-check bloquant sur CVE critique.",
  ],
  "prod": [
    "JVM dimensionnee aux limits conteneur (UseContainerSupport, Xmx coherent).",
    "Probes via actuator (liveness/readiness) et metriques Micrometer/Prometheus.",
    "GC adapte (G1/ZGC) selon latence/debit ; heap dumps automatiques sur OOM.",
    "Rolling updates Helm/K8s, deconnexion gracieuse (graceful shutdown).",
    "Diagnostic chaud (jcmd/jstack/jmap) sans redeployer.",
  ],
  "security": [
    "OWASP dependency-check/Snyk pour les CVE (Log4Shell-type) ; deps epinglees (BOM).",
    "Image non-root minimale ; pas de secret dans le jar/Dockerfile.",
    "Spring Security configure ; endpoints actuator proteges.",
    "SAST (SonarQube/SpotBugs) en CI ; validation stricte des entrees.",
    "TLS, RBAC et conformite PCI DSS pour les services bancaires.",
  ],
  "pitfalls": [
    "Heap non aligne aux cgroups : OOMKilled en conteneur.",
    "Deps non epinglees : CVE et builds non reproductibles.",
    "Actuator expose sans protection : fuite d'infos.",
    "Pas de readiness : trafic vers une app non prete.",
    "Tests d'integration absents (mock-only) : regressions en prod.",
  ],
  "practices": [
    "JDK LTS, wrapper Maven/Gradle, deps epinglees (BOM).",
    "Actuator probes + Micrometer/Prometheus.",
    "JVM alignee cgroups, GC adapte, graceful shutdown.",
    "SonarQube quality gate + dependency-check en CI.",
    "Image non-root minimale (Jib/multi-stage), promotion par digest.",
  ],
},
}
