# -*- coding: utf-8 -*-
"""Monitoring & observabilite."""

TECH = {
"prometheus": {
  "name": "Prometheus", "category": "Monitoring / Observ.",
  "role": "Prometheus est le systeme de monitoring et d'alerting open-source de reference cloud-native (CNCF gradue). Il collecte des metriques en mode pull via HTTP, les stocke dans une TSDB locale efficace, et les interroge avec PromQL. Service discovery Kubernetes, exporters, regles d'enregistrement/alerte et Alertmanager en font le socle de l'observabilite des plateformes conteneurisees et du suivi des SLO/SLI.",
  "commands": [
    ("promtool check config prometheus.yml", "Valider la configuration"),
    ("promtool check rules rules.yml", "Valider regles/alertes"),
    ("promtool test rules tests.yml", "Tests unitaires d'alertes"),
    ("curl localhost:9090/-/reload", "Recharger la conf a chaud"),
    ("curl 'localhost:9090/api/v1/query?query=up'", "Requete PromQL via API"),
    ("rate(http_requests_total[5m])", "Taux par seconde sur 5 min"),
    ("histogram_quantile(0.95, sum(rate(b_bucket[5m])) by (le))", "p95 de latence"),
    ("sum by (job)(up == 0)", "Cibles down par job"),
    ("amtool alert query", "Lister les alertes (Alertmanager)"),
    ("amtool silence add alertname=X", "Creer un silence"),
    ("curl localhost:9090/api/v1/targets", "Etat des cibles scrappees"),
    ("predict_linear(disk[1h], 4*3600) < 0", "Prediction de saturation"),
  ],
  "concepts": [
    "Modele pull : Prometheus scrappe des endpoints /metrics ; chaque serie = nom + labels (dimensions).",
    "Types : counter (monotone), gauge, histogram/summary (distributions, quantiles).",
    "PromQL : selection, agregation (sum/by), fonctions (rate/irate/increase) sur des plages temporelles.",
    "Service discovery (Kubernetes, Consul) decouvre dynamiquement les cibles.",
    "Recording rules pre-calculent les requetes couteuses ; alerting rules generent des alertes.",
    "Alertmanager : deduplication, regroupement, routage, silences, escalade.",
  ],
  "install": [
    "Kube-Prometheus-Stack (Helm) : Prometheus + Alertmanager + exporters + Grafana en un deploiement.",
    "Operator + ServiceMonitor/PodMonitor pour une decouverte declarative des cibles.",
    "Retention/taille TSDB dimensionnees ; remote_write vers stockage long terme (Thanos/Mimir).",
    "Exporters (node, blackbox, app via client libs) pour couvrir infra et applicatif.",
    "Regles et tests d'alertes versionnes (promtool test) des le depart.",
  ],
  "cicd": [
    "promtool check/test en CI : config et regles validees avant deploiement (alertes as code).",
    "Synthetic checks (blackbox exporter) integres pour valider la disponibilite en continu.",
    "Dashboards/alertes versionnes (GitOps) et promus comme du code.",
    "SLO/error budget calcules a partir des metriques pour piloter les releases.",
    "Alerte sur regression de KPI post-deploiement (gate d'observabilite).",
  ],
  "prod": [
    "HA : deux Prometheus identiques + Alertmanager en cluster (gossip) pour la deduplication.",
    "Stockage long terme (Thanos/Mimir) pour la retention et la vue globale multi-clusters.",
    "Cardinalite maitrisee : labels bornes (jamais d'ID/temps en label) sous peine d'explosion memoire.",
    "Recording rules pour des dashboards rapides ; federation/remote_write pour l'echelle.",
    "Alerting actionnable base SLO (symptomes utilisateur), pas bruit de causes.",
  ],
  "security": [
    "TLS + auth sur les endpoints ; isoler /metrics (pas d'expo publique).",
    "Secrets d'alerting (webhooks) hors config en clair (Vault/secret).",
    "RBAC sur l'Operator/ServiceMonitor ; multi-tenant via Thanos/Mimir.",
    "Pas d'info sensible en labels (PII) — fuite via les metriques.",
    "Audit des changements de regles via Git.",
  ],
  "pitfalls": [
    "Explosion de cardinalite (labels haute variabilite) : OOM Prometheus.",
    "Alertes sur causes, bruyantes : alerter sur symptomes/SLO.",
    "Pas de stockage long terme : perte d'historique.",
    "Pas de HA : trou de monitoring sur panne.",
    "Regles non testees (promtool test absent).",
  ],
  "practices": [
    "Kube-Prometheus-Stack + Operator (ServiceMonitor declaratif).",
    "Cardinalite bornee, recording rules, remote_write long terme.",
    "Alerting SLO actionnable, runbooks lies aux alertes.",
    "Regles/dashboards versionnes + promtool test en CI.",
    "HA Prometheus/Alertmanager, TLS/auth, pas de PII en labels.",
  ],
},

"grafana": {
  "name": "Grafana", "category": "Monitoring / Observ.",
  "role": "Grafana est la plateforme de visualisation et d'observabilite open-source. Elle agrege de multiples sources (Prometheus, Loki, Elasticsearch, SQL, Tempo) dans des dashboards interactifs, gere l'alerting unifie, les annotations et le provisioning as code. C'est l'outil de reference pour materialiser des dizaines de dashboards KPI infra/applicatifs et reduire drastiquement le temps de detection d'incidents.",
  "commands": [
    ("grafana-server --config grafana.ini", "Demarrer le serveur"),
    ("grafana cli plugins install PLUGIN", "Installer un plugin"),
    ("provisioning/datasources/*.yaml", "Datasources as code"),
    ("provisioning/dashboards/*.yaml", "Dashboards as code"),
    ("curl -H 'Authorization: Bearer T' /api/dashboards/db", "Importer un dashboard via API"),
    ("curl /api/health", "Verifier l'etat"),
    ("curl /api/datasources", "Lister les datasources"),
    ("grafana cli admin reset-admin-password ***", "Reinitialiser l'admin"),
    ("grafanactl / grizzly apply", "GitOps de dashboards"),
    ("curl /api/alertmanager/grafana/config/api/v1/alerts", "Config alerting unifie"),
    ("curl /api/annotations", "Annoter les deploiements"),
    ("dashboard JSON model (versionne en Git)", "Source de verite des dashboards"),
  ],
  "concepts": [
    "Datasources branchent Prometheus/Loki/ES/SQL/Tempo ; un dashboard correle metriques, logs et traces.",
    "Panels + variables (templating) rendent les dashboards reutilisables et filtrables.",
    "Alerting unifie (regles, contact points, notification policies) independant de la datasource.",
    "Provisioning as code : datasources/dashboards/alertes en YAML/JSON versionnes.",
    "Annotations marquent les deploiements pour correler cause/effet.",
    "RBAC + organisations/folders pour le multi-equipe.",
  ],
  "install": [
    "Deploiement via Helm (kube-prometheus-stack) ; provisioning as code des datasources/dashboards.",
    "Auth SSO (OIDC) + RBAC folders par equipe des le depart.",
    "Stockage de conf externalise (DB) pour la HA.",
    "Bibliotheque de dashboards standard (USE/RED) reutilisables.",
    "Alerting unifie configure (contact points, policies) versionne.",
  ],
  "cicd": [
    "Dashboards/alertes en JSON/YAML versionnes et appliques via GitOps (grizzly/provisioning).",
    "Annotations automatiques de deploiement (API) pour correler releases et incidents.",
    "Validation des dashboards (lint JSON model) en CI.",
    "Promotion identique entre environnements (memes dashboards parametres).",
    "Synthetic/alerting changes revus en PR.",
  ],
  "prod": [
    "HA : repliques + base externe ; cache des datasources.",
    "Dashboards RED/USE actionnables, lies aux runbooks.",
    "Variables/templating pour couvrir N services sans duplication.",
    "Alerting unifie route vers les bons canaux (escalade).",
    "Performance : limiter les panels/requetes lourdes, recording rules en amont.",
  ],
  "security": [
    "SSO/OIDC + RBAC folders ; pas d'anonymous edit en prod.",
    "Secrets datasources chiffres (provisioning + secret manager).",
    "Reverse proxy TLS ; pas d'expo publique non protegee.",
    "Audit des changements via Git (dashboards as code).",
    "Eviter l'affichage de PII dans les panels.",
  ],
  "pitfalls": [
    "Dashboards crees a la main non versionnes : perte/derive.",
    "Requetes lourdes saturant la datasource : pre-agreger.",
    "Alerting fragmente par datasource : utiliser l'alerting unifie.",
    "Anonymous/admin partage : risque securite.",
    "Trop de panels = dashboards illisibles.",
  ],
  "practices": [
    "Provisioning as code (datasources/dashboards/alertes) versionne.",
    "Dashboards RED/USE actionnables + runbooks + annotations de deploiement.",
    "SSO/OIDC + RBAC folders, secrets chiffres.",
    "Alerting unifie avec policies/escalade.",
    "Recording rules en amont pour la performance.",
  ],
},

"elk": {
  "name": "ELK Stack", "category": "Monitoring / Observ.",
  "role": "La suite ELK (Elasticsearch, Logstash, Kibana) + Beats est la plateforme de gestion centralisee des logs et de recherche. Elasticsearch indexe et recherche a grande echelle, Logstash/Beats ingerent et transforment, Kibana visualise et explore. C'est l'outil de reference pour centraliser les logs applicatifs/infra, construire des dashboards KPI qualite/performance et accelerer le diagnostic d'incidents.",
  "commands": [
    ("curl localhost:9200/_cluster/health?pretty", "Sante du cluster ES"),
    ("curl localhost:9200/_cat/indices?v", "Lister les indices"),
    ("curl localhost:9200/_cat/nodes?v", "Etat des noeuds"),
    ("curl -XPUT localhost:9200/_ilm/policy/p -d @p.json", "Politique ILM (retention)"),
    ("curl -XPUT localhost:9200/_index_template/t -d @t.json", "Template d'index"),
    ("filebeat -e -c filebeat.yml", "Demarrer Filebeat"),
    ("logstash -f pipeline.conf --config.test_and_exit", "Valider un pipeline"),
    ("GET index/_search { query }", "Recherche (DSL)"),
    ("POST _reindex { source, dest }", "Reindexer"),
    ("curl localhost:5601/api/status", "Etat de Kibana"),
    ("curl localhost:9200/_nodes/stats", "Metriques de noeuds"),
    ("curl -XDELETE localhost:9200/old-*", "Purger d'anciens indices"),
  ],
  "concepts": [
    "Elasticsearch : index inverse distribue (shards/replicas) pour recherche/agregation a l'echelle.",
    "Beats (Filebeat/Metricbeat) collectent ; Logstash/ingest pipelines parsent et enrichissent.",
    "Kibana : exploration (Discover), dashboards, Lens, alerting.",
    "Mapping/index templates : typer les champs ; ECS standardise le schema.",
    "ILM (hot/warm/cold/delete) gere le cycle de vie et la retention des indices.",
    "Data streams pour les logs append-only ; rollover automatique.",
  ],
  "install": [
    "Cluster ES dedie (master/data/ingest) dimensionne ; heap = 50% RAM, max ~31 Go.",
    "Index templates ECS + ILM (retention) configures des le depart.",
    "Beats deployes en DaemonSet (Kubernetes) ; Logstash si transformation lourde.",
    "Kibana derriere SSO/TLS ; spaces/roles par equipe.",
    "Snapshots vers stockage objet (sauvegarde/DR) planifies.",
  ],
  "cicd": [
    "Pipelines de parsing (grok/ingest) versionnes et testes (config.test_and_exit).",
    "Dashboards/saved objects exportes en Git et importes par environnement.",
    "Logs structures (JSON/ECS) imposes cote applicatif pour l'exploitabilite.",
    "Index templates/ILM appliques as code.",
    "Alerting (Kibana) revu en PR.",
  ],
  "prod": [
    "Shards bien dimensionnes (taille cible 10-50 Go) ; eviter l'over-sharding.",
    "ILM hot/warm/cold + snapshots : maitrise du cout et de la retention.",
    "Replicas pour la HA ; isolation des roles de noeuds.",
    "Surveillance du cluster (statut, heap, JVM GC) et alerting.",
    "Dimensionnement capacitaire selon le debit de logs (Go/jour).",
  ],
  "security": [
    "Security pack active (auth/TLS/RBAC) — jamais de cluster ouvert.",
    "Chiffrement in transit/at rest ; reseau prive.",
    "Roles/spaces Kibana au moindre privilege.",
    "Masquage/anonymisation des PII a l'ingestion (conformite).",
    "Snapshots chiffres ; audit des acces.",
  ],
  "pitfalls": [
    "Over-sharding / mapping explosion : cluster instable.",
    "Heap > 31 Go ou > 50% RAM : GC pathologique.",
    "Pas d'ILM : indices infinis, cout/perf degrades.",
    "Cluster sans securite expose : fuite massive de logs.",
    "Logs non structures : parsing fragile.",
  ],
  "practices": [
    "ECS + index templates + ILM des le depart.",
    "Shards dimensionnes, heap <=31 Go/50% RAM.",
    "Security (TLS/RBAC) obligatoire, PII masquees.",
    "Snapshots chiffres/testes, roles de noeuds isoles.",
    "Logs structures applicatifs, pipelines testes/versionnes.",
  ],
},

"datadog": {
  "name": "Datadog", "category": "Monitoring / Observ.",
  "role": "Datadog est une plateforme SaaS d'observabilite unifiee : metriques, logs, traces (APM), RUM, profiling, synthetics et securite, correles dans une seule interface. L'Agent collecte automatiquement metriques et traces, l'auto-instrumentation et 700+ integrations accelerent la mise en observabilite, et les monitors/SLO industrialisent l'alerting — adapte aux environnements ou un time-to-value rapide prime.",
  "commands": [
    ("DD_API_KEY=... bash -c \"$(curl -L install_script)\"", "Installer l'Agent"),
    ("datadog-agent status", "Etat de l'Agent et des checks"),
    ("datadog-agent configcheck", "Verifier la configuration des checks"),
    ("datadog-agent check NAME", "Executer un check manuellement"),
    ("helm install datadog datadog/datadog -f values.yaml", "Deployer sur Kubernetes"),
    ("DD_APM_ENABLED=true DD_ENV=prod", "Activer l'APM / tagging"),
    ("datadog-ci synthetics run-tests", "Synthetics en CI"),
    ("datadog-ci junit upload report.xml", "Remonter resultats de tests"),
    ("dogshell / api: POST /api/v1/monitor", "Monitors as code via API"),
    ("terraform (datadog provider)", "Monitors/dashboards as code"),
    ("DD_LOGS_ENABLED=true", "Activer la collecte de logs"),
    ("datadog-agent flare", "Bundle de diagnostic support"),
  ],
  "concepts": [
    "Plateforme unifiee : metriques + logs + traces APM + RUM correles par tags (env/service/version).",
    "Agent + integrations (700+) : autodiscovery des conteneurs/services.",
    "Unified Service Tagging (env, service, version) : pivot entre tous les signaux.",
    "Monitors (metric/log/APM/synthetic) + SLO + composite ; gestion d'alerting riche.",
    "APM : tracing distribue, flame graphs, profiling continu.",
    "As code : provider Terraform / API pour monitors/dashboards.",
  ],
  "install": [
    "Agent en DaemonSet (Helm) avec autodiscovery ; Unified Service Tagging impose.",
    "Logs/APM actives selectivement ; controle des volumes (cout).",
    "Monitors/dashboards/SLO en Terraform (datadog provider) versionnes.",
    "RBAC + teams + tags d'ownership des le depart.",
    "Index/retention de logs et sampling APM configures (FinOps).",
  ],
  "cicd": [
    "datadog-ci : synthetics et upload de resultats de tests dans le pipeline.",
    "Monitors/dashboards as code (Terraform) promus entre environnements.",
    "Markers de deploiement (version tag) pour correler releases et regressions.",
    "Gate sur SLO/erreurs post-deploiement (qualite d'observabilite).",
    "Sampling/quotas pilotes pour maitriser le cout en CI/preprod.",
  ],
  "prod": [
    "SLO + monitors composites actionnables ; escalade et on-call (PagerDuty).",
    "Tracing distribue pour le MTTR (cause racine rapide).",
    "Watchdog/anomalies pour la detection proactive.",
    "Controle du cout : sampling, index de logs, exclusion du bruit.",
    "Tagging coherent = correlation fiable en incident.",
  ],
  "security": [
    "Cles API/APP en secret (Vault) ; rotation ; scoping par role.",
    "Sensitive Data Scanner pour masquer les PII dans les logs.",
    "RBAC/teams au moindre privilege ; SSO.",
    "Donnees SaaS : verifier residence/conformite (region EU).",
    "Audit trail des changements de monitors.",
  ],
  "pitfalls": [
    "Cout non maitrise (logs/APM custom metrics) : sampling/quotas requis.",
    "Tagging incoherent : correlation cassee.",
    "Monitors crees a la main non versionnes : derive.",
    "PII non masquee dans les logs.",
    "Cles API en clair.",
  ],
  "practices": [
    "Unified Service Tagging systematique.",
    "Monitors/dashboards/SLO as code (Terraform).",
    "FinOps : sampling, quotas, index de logs.",
    "Sensitive Data Scanner, secrets en Vault, RBAC/SSO.",
    "Deploy markers + gates SLO en CI/CD.",
  ],
},

"loki": {
  "name": "Grafana Loki", "category": "Monitoring / Observ.",
  "role": "Loki est le systeme d'agregation de logs de Grafana Labs, concu comme 'Prometheus pour les logs' : il n'indexe pas le contenu mais seulement un petit jeu de labels, ce qui le rend tres economique et scalable. Couple a Promtail/Alloy pour la collecte et a Grafana pour l'exploration (LogQL), il correle nativement logs et metriques par labels — ideal pour une observabilite cloud-native a cout maitrise.",
  "commands": [
    ("logcli query '{app=\"api\"} |= \"error\"'", "Requete LogQL en CLI"),
    ("logcli labels", "Lister les labels disponibles"),
    ("curl localhost:3100/ready", "Verifier la disponibilite"),
    ("curl localhost:3100/metrics", "Metriques Loki"),
    ("promtail -config.file=promtail.yaml", "Collecteur Promtail"),
    ("helm install loki grafana/loki -f values.yaml", "Deployer (Helm)"),
    ("{job=\"k8s\"} | json | level=\"error\"", "Parsing + filtre LogQL"),
    ("sum(rate({app=\"api\"} |= \"5xx\" [5m]))", "Metrique derivee de logs"),
    ("curl '/loki/api/v1/query_range?query=...'", "API de requete"),
    ("logcli series '{namespace=\"prod\"}'", "Series par labels"),
    ("curl -XPOST /loki/api/v1/push", "Ingestion directe"),
    ("compactor / retention config", "Retention et compaction"),
  ],
  "concepts": [
    "Index minimal sur labels uniquement ; le contenu est stocke compresse en chunks (objet/S3).",
    "LogQL : selection par labels puis filtres/parsers (json/logfmt/regexp) sur le flux.",
    "Memes labels que Prometheus -> correlation logs/metriques immediate dans Grafana.",
    "Promtail/Alloy collectent (decouverte Kubernetes) ; pas de schema lourd a maintenir.",
    "Architecture micro-services (distributor/ingester/querier) ou mono-binaire selon l'echelle.",
    "Cout faible : stockage objet + index leger (vs ELK plein-texte).",
  ],
  "install": [
    "Helm (loki + promtail/alloy) ; backend stockage objet (S3/GCS) + retention via compactor.",
    "Labels low-cardinality stricts (app/namespace/pod) — jamais d'ID en label.",
    "Multi-tenant (X-Scope-OrgID) si plusieurs equipes.",
    "Limits (ingestion rate, max streams) configurees des le depart.",
    "Datasource Grafana + dashboards correlant logs/metriques.",
  ],
  "cicd": [
    "Logs applicatifs structures (JSON) imposes pour un parsing LogQL fiable.",
    "Config Promtail/Loki versionnee et appliquee via GitOps.",
    "Alerting (Loki ruler) sur patterns d'erreurs as code.",
    "Correlation deploiement/erreurs via labels version.",
    "Limits/retention revues en PR (FinOps).",
  ],
  "prod": [
    "Cardinalite de labels strictement bornee : sinon explosion d'index/memoire.",
    "Stockage objet + retention/compaction : cout maitrise a grande echelle.",
    "Mode micro-services + cache pour la scalabilite des requetes.",
    "Correlation logs/metriques accelere le MTTR.",
    "Limits anti-abus (rate, streams) pour proteger le cluster.",
  ],
  "security": [
    "Multi-tenant isole (OrgID) ; auth/TLS via gateway.",
    "Pas de PII en labels ; masquage a la collecte si necessaire.",
    "Acces stockage objet restreint (IAM minimal).",
    "RBAC Grafana cote exploration.",
    "Audit des regles d'alerting via Git.",
  ],
  "pitfalls": [
    "Labels haute cardinalite (ID/IP) : Loki s'effondre.",
    "Logs non structures : LogQL fragile.",
    "Pas de retention/limits : cout et instabilite.",
    "Mono-binaire en forte charge : passer en micro-services.",
    "PII en labels.",
  ],
  "practices": [
    "Labels low-cardinality stricts, logs structures JSON.",
    "Stockage objet + retention/compaction (FinOps).",
    "Multi-tenant + limits anti-abus.",
    "Correlation logs/metriques par labels dans Grafana.",
    "Config/alertes versionnees (GitOps).",
  ],
},
}
