# -*- coding: utf-8 -*-
"""Securite DevSecOps."""

TECH = {
"sonarqube": {
  "name": "SonarQube", "category": "Securite DevSecOps",
  "role": "SonarQube est la plateforme d'inspection continue de la qualite et de la securite du code (SAST). Elle analyse 30+ langages pour detecter bugs, vulnerabilites, hotspots de securite, code smells et mesurer la couverture et la duplication. Le concept de Quality Gate, applique au code nouveau (Clean as You Code), bloque la livraison tant que les criteres ne sont pas remplis — un controle qualite/securite incontournable des pipelines bancaires.",
  "commands": [
    ("sonar-scanner -Dsonar.projectKey=app -Dsonar.host.url=URL", "Lancer une analyse"),
    ("mvn sonar:sonar -Dsonar.token=$T", "Analyse via Maven"),
    ("./gradlew sonar", "Analyse via Gradle"),
    ("sonar.qualitygate.wait=true", "Bloquer le pipeline sur le gate"),
    ("docker run -d -p 9000:9000 sonarqube:lts-community", "Lancer le serveur"),
    ("curl -u T: '/api/qualitygates/project_status?projectKey=app'", "Statut du Quality Gate"),
    ("sonar.coverage.exclusions=**/test/**", "Exclusions de couverture"),
    ("sonar.pullrequest.key=$PR", "Analyse de Pull Request (decoration)"),
    ("sonar.exclusions=**/generated/**", "Exclure du code genere"),
    ("curl '/api/issues/search?severities=BLOCKER'", "Lister les issues critiques"),
    ("curl '/api/measures/component?metricKeys=coverage'", "Metriques projet"),
    ("sonar.branch.name=$BRANCH", "Analyse multi-branches"),
  ],
  "concepts": [
    "SAST multi-langage : bugs, vulnerabilites, security hotspots, code smells, duplication, couverture.",
    "Quality Gate : ensemble de conditions (gate par defaut 'Sonar way') qui passe/echoue une analyse.",
    "Clean as You Code : criteres appliques au New Code (depuis une reference) — la dette legacy n'est pas bloquante.",
    "Decoration de Pull Request : feedback inline directement dans GitHub/GitLab.",
    "La couverture vient des rapports de tests (JaCoCo/lcov) importes, Sonar ne l'execute pas.",
    "Profils de qualite (regles activees) et portails de gouvernance multi-projets.",
  ],
  "install": [
    "Serveur + base externe (Postgres) ; Elasticsearch embarque -> vm.max_map_count regle.",
    "LTS, stockage persistant, reverse proxy TLS ; auth SSO/LDAP.",
    "Profils de qualite et Quality Gate adaptes (centres sur le New Code).",
    "Tokens d'analyse par projet (secret CI), pas d'identifiants partages.",
    "Plugins langage requis installes et figes.",
  ],
  "cicd": [
    "Etape obligatoire post-tests : import couverture -> analyse -> sonar.qualitygate.wait=true (gate bloquante).",
    "Analyse de PR avec decoration : pas de merge si le gate du New Code echoue.",
    "Token en secret CI ; cache du scanner pour la vitesse.",
    "Echec du pipeline = retour developpeur immediat (shift-left securite/qualite).",
    "Tendances qualite suivies comme KPI (Grafana via API).",
  ],
  "prod": [
    "Serveur dimensionne (ES/heap) ; sauvegardes DB testees.",
    "Gouvernance multi-projets (portfolios) et profils homogenes.",
    "Retention/menage des analyses pour la performance.",
    "Disponibilite : le gate est sur le chemin critique de livraison.",
    "Suivi de la dette et du taux de remediation comme indicateurs.",
  ],
  "security": [
    "Detection SAST + hotspots a revoir manuellement (revue de securite tracee).",
    "Tokens scopes par projet, rotation ; pas d'admin partage.",
    "TLS + SSO/LDAP ; RBAC par projet.",
    "Integration de la conformite (regles PCI/OWASP activees).",
    "Audit des changements de Quality Gate/profil.",
  ],
  "pitfalls": [
    "Gate sur tout le code (legacy) : bloque tout — cibler le New Code.",
    "Couverture non importee : metrique a 0.",
    "vm.max_map_count non regle : ES/Sonar ne demarre pas.",
    "qualitygate.wait absent : analyse non bloquante (gate cosmetique).",
    "Hotspots ignores : faux sentiment de securite.",
  ],
  "practices": [
    "Clean as You Code : gate sur le New Code.",
    "qualitygate.wait=true bloquant + decoration de PR.",
    "Couverture importee (JaCoCo/lcov), exclusions justifiees.",
    "Tokens scopes/rotates, TLS/SSO/RBAC.",
    "Hotspots revus, tendances suivies en KPI.",
  ],
},

"trivy": {
  "name": "Trivy", "category": "Securite DevSecOps",
  "role": "Trivy (Aqua Security) est un scanner de securite open-source tout-en-un, rapide et sans serveur : images conteneur, systemes de fichiers, depots Git, IaC (Terraform/K8s/Dockerfile), licences et secrets. Il detecte les vulnerabilites (CVE OS + dependances applicatives) et les misconfigurations, et genere des SBOM — un maillon central du DevSecOps shift-left et de la securisation de la chaine d'approvisionnement.",
  "commands": [
    ("trivy image reg/app:1.2.0", "Scanner une image conteneur"),
    ("trivy image --severity HIGH,CRITICAL --exit-code 1 IMG", "Echouer le build sur CVE grave"),
    ("trivy fs --scanners vuln,secret,misconfig .", "Scanner le code/projet"),
    ("trivy config ./terraform", "Scanner l'IaC (misconfig)"),
    ("trivy repo https://github.com/org/repo", "Scanner un depot"),
    ("trivy k8s --report summary cluster", "Scanner un cluster Kubernetes"),
    ("trivy image --format cyclonedx -o sbom.json IMG", "Generer un SBOM"),
    ("trivy image --ignore-unfixed IMG", "Ignorer les CVE sans correctif"),
    ("trivy image --format sarif -o r.sarif IMG", "Sortie SARIF (GitHub Security)"),
    ("trivy --cache-dir .cache image IMG", "Cache de la base de vulns"),
    ("trivy convert --format table r.json", "Convertir un rapport"),
    (".trivyignore", "Acceptation tracee de findings"),
  ],
  "concepts": [
    "Scanner unifie : vulnerabilites (OS + libs applicatives), misconfig IaC, secrets, licences, SBOM.",
    "Sans serveur : un binaire, base de vulns mise a jour automatiquement (cache possible).",
    "Exit codes pilotables : echouer le pipeline selon la severite (gate securite).",
    "Formats : table, JSON, SARIF (GitHub), CycloneDX/SPDX (SBOM).",
    "--ignore-unfixed reduit le bruit ; .trivyignore trace les acceptations de risque.",
    "Cible images, fs, repo, IaC, Kubernetes — couverture supply chain large.",
  ],
  "install": [
    "Binaire/conteneur ; mettre en cache la DB de vulnerabilites pour les jobs CI.",
    "Definir une politique de severite (HIGH/CRITICAL bloquant) et --ignore-unfixed.",
    ".trivyignore versionne avec justification/expiration des exceptions.",
    "Integration Operator (trivy-operator) pour le scan continu en cluster.",
    "Sorties SARIF remontees au tableau de bord securite (GitHub/GitLab).",
  ],
  "cicd": [
    "Gate : scan image avant push registry, --exit-code 1 sur HIGH/CRITICAL.",
    "Scan IaC (trivy config) et secrets en complement du SAST.",
    "SBOM (CycloneDX) genere et archive pour la tracabilite supply chain.",
    "Resultats SARIF dans l'onglet Security ; PR bloquee sur findings.",
    "Cache DB pour des scans rapides et resilients (offline-friendly).",
  ],
  "prod": [
    "trivy-operator : scan continu des charges en cluster + reports CRD.",
    "Politique d'admission refusant les images non scannees/vulnerables.",
    "Re-scan periodique (nouvelles CVE sur images deja deployees).",
    "Tableau de bord de posture (severites, tendances) suivi en KPI.",
    "SBOM conserve pour reponse rapide aux CVE type Log4Shell.",
  ],
  "security": [
    "Detection CVE + secrets + misconfig = defense en profondeur shift-left.",
    "Acceptations de risque tracees/expirantes (.trivyignore revue).",
    "Couple a la signature (Cosign) et a l'admission policy.",
    "Pas de secret dans les images (scanner secret le verifie).",
    "Conformite PCI DSS : scan obligatoire avant promotion.",
  ],
  "pitfalls": [
    "Scan informatif non bloquant : ajouter --exit-code 1.",
    "Bruit des CVE non corrigeables : --ignore-unfixed + tri par severite.",
    ".trivyignore fourre-tout sans justification : dette de securite cachee.",
    "Pas de re-scan : images deployees vulnerables aux nouvelles CVE.",
    "DB non cachee : jobs lents/fragiles hors-ligne.",
  ],
  "practices": [
    "Gate bloquant HIGH/CRITICAL, --ignore-unfixed pour le bruit.",
    ".trivyignore versionne, justifie, expirant.",
    "SBOM genere/archive, sortie SARIF au dashboard securite.",
    "trivy-operator + admission policy en cluster.",
    "Re-scan periodique, signature Cosign couplee.",
  ],
},
}
