# -*- coding: utf-8 -*-
"""Tests automatises."""

TECH = {
"robot-framework": {
  "name": "Robot Framework", "category": "Tests automatises",
  "role": "Robot Framework est un framework d'automatisation de tests generique, base sur des mots-cles (keyword-driven), extensible par bibliotheques Python/Java. Sa syntaxe tabulaire lisible (proche du langage naturel) supporte les tests d'acceptation, E2E, API et RPA. Avec SeleniumLibrary, RequestsLibrary et des bibliotheques metier, il valide des flux complexes (XML bancaires, ISO 8583, E2E SSH) et s'integre nativement aux pipelines CI.",
  "commands": [
    ("robot tests/", "Executer une suite"),
    ("robot -i smoke -e wip tests/", "Inclure/exclure par tags"),
    ("robot -v ENV:prod tests/", "Injecter des variables"),
    ("robot --outputdir results tests/", "Repertoire de rapports"),
    ("robot --rerunfailed output.xml -o rerun.xml tests/", "Rejouer les echecs"),
    ("rebot --merge output1.xml output2.xml", "Fusionner des resultats (parallele)"),
    ("pabot --processes 4 tests/", "Execution parallele (Pabot)"),
    ("robot --listener allure_robotframework tests/", "Rapport Allure"),
    ("robot --dryrun tests/", "Verifier sans executer"),
    ("pip install robotframework robotframework-seleniumlibrary", "Installation"),
    ("robot --loglevel DEBUG tests/", "Logs detailles"),
    ("robot --variablefile env.py tests/", "Variables depuis un fichier"),
  ],
  "concepts": [
    "Keyword-driven : tests = sequences de mots-cles lisibles ; mots-cles bas niveau dans des libs Python.",
    "Architecture en couches : suites -> resources/keywords metier -> bibliotheques techniques.",
    "Bibliotheques : SeleniumLibrary (UI), RequestsLibrary (API), DatabaseLibrary, SSHLibrary, custom Python.",
    "Tags pour filtrer/organiser (smoke/regression) ; data-driven (Templates) pour les jeux de donnees.",
    "Rapports HTML/XML riches (log.html, report.html) ; integration Allure.",
    "Variables/environnements externalises ; setup/teardown a tous les niveaux.",
  ],
  "install": [
    "pip install robotframework + libs ; structurer tests/, resources/, libraries/.",
    "Page Object/keyword metier pour la maintenabilite (pas de selecteurs en dur dans les tests).",
    "Variables d'environnement externalisees (variablefile) ; pas de secret en dur.",
    "Pabot pour le parallelisme ; conteneuriser l'execution (Selenium Grid/browsers).",
    "Conventions de tags et de nommage des le depart.",
  ],
  "cicd": [
    "Etape CI : robot --outputdir + tags ; publication JUnit/Allure dans le pipeline.",
    "Execution Dockerisee parallele (Pabot) pour reduire le temps de suite (-50%+).",
    "Smoke en gate de deploiement, regression complete en nocturne.",
    "rerunfailed + rebot --merge pour la robustesse face aux flaky.",
    "Validation des flux bancaires (XML/ISO 8583) et E2E SSH integree au pipeline.",
  ],
  "prod": [
    "Synthetic/monitoring tests rejoues en continu pour valider les services critiques.",
    "Suites stables (waits explicites, pas de sleep) pour un signal fiable.",
    "Parallelisme + sharding pour passer a l'echelle.",
    "Rapports archives (tracabilite reglementaire des campagnes).",
    "Couverture fonctionnelle suivie comme KPI qualite.",
  ],
  "security": [
    "Secrets via variables d'environnement/Vault, jamais dans les .robot.",
    "Donnees de test anonymisees (pas de PII/production).",
    "Execution isolee (conteneurs ephemeres) sans acces prod superflu.",
    "Logs nettoyes des valeurs sensibles (no log des mots de passe).",
    "Acces aux environnements de test au moindre privilege.",
  ],
  "pitfalls": [
    "Sleep au lieu de waits explicites : suites lentes et flaky.",
    "Selecteurs/données en dur : maintenance impossible.",
    "Secrets dans les fichiers de test.",
    "Pas de tags : impossible de cibler smoke/regression.",
    "Pas de parallelisme : feedback trop lent.",
  ],
  "practices": [
    "Keywords metier + Page Object, waits explicites.",
    "Variables/secrets externalises (Vault), donnees anonymisees.",
    "Tags (smoke/regression), data-driven pour les jeux de donnees.",
    "Pabot + Docker (parallele), Allure/JUnit en CI.",
    "rerunfailed + merge, suites stables comme signal de gate.",
  ],
},

"playwright": {
  "name": "Playwright", "category": "Tests automatises",
  "role": "Playwright (Microsoft) est un framework moderne de tests end-to-end multi-navigateurs (Chromium, Firefox, WebKit) en TypeScript/Python/Java/.NET. Auto-waiting intelligent, isolation par contexte de navigateur, tracing, intercep­tion reseau et parallelisme natif eliminent une grande part des tests flaky. C'est un standard actuel pour des suites E2E rapides, fiables et integrees au CI.",
  "commands": [
    ("npm init playwright@latest", "Initialiser un projet"),
    ("npx playwright test", "Executer la suite"),
    ("npx playwright test --project=chromium -g 'login'", "Filtrer projet/test"),
    ("npx playwright test --ui", "Mode UI interactif"),
    ("npx playwright codegen URL", "Generer un test par enregistrement"),
    ("npx playwright show-report", "Ouvrir le rapport HTML"),
    ("npx playwright test --trace on", "Capturer un trace debuggable"),
    ("npx playwright show-trace trace.zip", "Visualiser le trace"),
    ("npx playwright test --shard=1/4", "Sharding pour le parallelisme CI"),
    ("npx playwright install --with-deps", "Installer navigateurs + deps"),
    ("PWDEBUG=1 npx playwright test", "Debug pas a pas"),
    ("npx playwright test --reporter=junit", "Rapport JUnit pour CI"),
  ],
  "concepts": [
    "Auto-waiting : Playwright attend l'actionnabilite des elements -> beaucoup moins de flaky.",
    "BrowserContext isole (cookies/storage) : tests independants, parallelisme sur.",
    "Locators robustes (role/text/testid) plutot que selecteurs CSS fragiles.",
    "Network interception/mocking pour des tests deterministes.",
    "Trace viewer (DOM/réseau/console) : diagnostic post-mortem puissant.",
    "Parallelisme natif + sharding ; multi-navigateurs reels.",
  ],
  "install": [
    "npm init playwright ; playwright install --with-deps (ou image officielle en CI).",
    "Page Object Model + locators role/testid pour la maintenabilite.",
    "Fixtures pour l'etat (auth via storageState reutilise).",
    "Config projets par navigateur ; baseURL/env externalises.",
    "trace: on-first-retry et reporters (HTML+JUnit) configures.",
  ],
  "cicd": [
    "Image Docker officielle Playwright ; sharding (--shard) pour reduire le temps.",
    "trace/screenshots/videos on-first-retry archives comme artefacts CI.",
    "Smoke en gate de deploiement, suite complete en parallele.",
    "Rapport JUnit publie ; flaky tracke (retries bornes, pas masques).",
    "Mock reseau pour stabiliser les dependances externes.",
  ],
  "prod": [
    "Synthetic monitoring (parcours critiques) rejoues en continu.",
    "Suites rapides/fiables = feedback de release fiable.",
    "Isolation par contexte : pas de pollution inter-tests a l'echelle.",
    "Retries cibles + analyse de flaky comme indicateur qualite.",
    "Artefacts (trace) acceleres le MTTR des regressions UI.",
  ],
  "security": [
    "Secrets/credentials via env, jamais dans le code de test.",
    "storageState (sessions) non committe ; donnees de test anonymisees.",
    "Execution isolee (conteneurs ephemeres).",
    "Mock des services sensibles plutot que cibler la prod.",
    "Nettoyage des artefacts pouvant contenir des donnees.",
  ],
  "pitfalls": [
    "Selecteurs CSS fragiles : preferer role/testid.",
    "sleep manuels au lieu de l'auto-wait.",
    "Tests dependants entre eux (etat partage).",
    "Retries infinis masquant des bugs reels.",
    "Secrets dans le repo / storageState committe.",
  ],
  "practices": [
    "Locators role/testid + POM, auto-wait (pas de sleep).",
    "Contextes isoles, fixtures d'auth (storageState).",
    "Sharding + image officielle en CI, trace on-first-retry.",
    "Retries bornes, flaky analyse (non masque).",
    "Secrets via env, donnees anonymisees.",
  ],
},

"cypress": {
  "name": "Cypress", "category": "Tests automatises",
  "role": "Cypress est un framework de tests E2E/composant JavaScript execute dans le navigateur, reconnu pour son experience developpeur : time-travel, rechargement instantane, retry-ability des assertions et debugging visuel. Adapte aux applications web modernes (SPA), il fournit des suites de regression et E2E rapides a ecrire, integrees au CI avec parallelisation (Cypress Cloud).",
  "commands": [
    ("npm i -D cypress && npx cypress open", "Installer / mode interactif"),
    ("npx cypress run", "Execution headless (CI)"),
    ("npx cypress run --browser chrome --spec 'e2e/login.cy.js'", "Cibler navigateur/spec"),
    ("npx cypress run --record --parallel --key K", "Parallelisation (Cypress Cloud)"),
    ("npx cypress run --env api=URL", "Variables d'environnement"),
    ("cypress run --reporter junit", "Rapport JUnit"),
    ("cy.intercept('GET','/api/**',{fixture:'x.json'})", "Mock reseau"),
    ("cy.session(id, setup)", "Cache de session (auth)"),
    ("cy.get('[data-cy=submit]').click()", "Selecteur data-cy stable"),
    ("npx cypress verify / info", "Diagnostic installation"),
    ("cypress run --config retries=2", "Retries sur flaky"),
    ("cy.task / cy.exec", "Hooks Node (DB seeding)"),
  ],
  "concepts": [
    "S'execute dans le navigateur, meme boucle d'evenements que l'app : controle et debug fins.",
    "Retry-ability : les assertions/commandes reessaient jusqu'au timeout -> moins de flaky.",
    "cy.intercept pour mocker/observer le reseau (tests deterministes).",
    "cy.session met en cache l'authentification entre tests (rapidite).",
    "Selecteurs data-cy dedies pour decoupler des classes/styles.",
    "Time-travel/snapshots dans le runner : diagnostic visuel immediat.",
  ],
  "install": [
    "npm i -D cypress ; structurer e2e/, fixtures/, support/ ; commandes custom.",
    "Selecteurs data-cy convenus avec les developpeurs.",
    "baseUrl/env externalises ; pas de secret en dur.",
    "Seeding via cy.task/cy.exec pour un etat deterministe.",
    "Retries config + reporters (JUnit) des le depart.",
  ],
  "cicd": [
    "cypress run headless ; image Docker Cypress en CI.",
    "Parallelisation (Cypress Cloud --record --parallel) pour reduire le temps de regression.",
    "Artefacts (videos/screenshots d'echec) archives ; rapport JUnit publie.",
    "Smoke en gate, regression complete parallelisee.",
    "Mock reseau pour stabiliser les dependances externes.",
  ],
  "prod": [
    "Suites de regression sur interfaces critiques (monitoring) — -50% temps de validation.",
    "Tests stables = signal de gate fiable.",
    "Parallelisation pour passer a l'echelle.",
    "Flaky tracke (retries bornes) comme KPI.",
    "Videos/snapshots acceleres le diagnostic des regressions.",
  ],
  "security": [
    "Secrets via Cypress.env/CI, jamais committes.",
    "Donnees de test anonymisees ; pas de cible production.",
    "Execution isolee (conteneurs).",
    "Nettoyage des artefacts (videos) potentiellement sensibles.",
    "Acces environnements de test au moindre privilege.",
  ],
  "pitfalls": [
    "Selecteurs fragiles (classes CSS) : utiliser data-cy.",
    "cy.wait(temps fixe) au lieu d'attendre une condition/intercept.",
    "Tests interdependants (etat partage).",
    "Limitation cross-origin/onglets mal anticipee.",
    "Secrets en dur dans les specs.",
  ],
  "practices": [
    "Selecteurs data-cy, retry-ability (pas de wait fixe).",
    "cy.session pour l'auth, cy.intercept pour le determinisme.",
    "Seeding via cy.task, tests independants.",
    "Parallelisation CI + artefacts d'echec, JUnit.",
    "Secrets via env, donnees anonymisees.",
  ],
},

"selenium": {
  "name": "Selenium", "category": "Tests automatises",
  "role": "Selenium est le standard historique d'automatisation des navigateurs via le protocole W3C WebDriver. Multi-langage (Java/Python/C#/JS) et multi-navigateurs, il pilote des navigateurs reels et, via Selenium Grid, distribue l'execution a grande echelle. Mature et universel, il reste central pour la compatibilite cross-browser et l'integration de tests UI dans des pipelines CI heterogenes.",
  "commands": [
    ("pip install selenium / Maven selenium-java", "Installer le binding"),
    ("docker run -d -p 4444:4444 selenium/standalone-chrome", "Grid/standalone conteneurise"),
    ("docker run selenium/hub + node-chrome", "Selenium Grid (hub + nodes)"),
    ("webdriver-manager (auto driver)", "Gerer les drivers"),
    ("driver.get(url)", "Naviguer"),
    ("WebDriverWait(d,10).until(EC.element_to_be_clickable(...))", "Attente explicite"),
    ("driver.find_element(By.CSS_SELECTOR, s)", "Localiser un element"),
    ("RemoteWebDriver(hub_url, options)", "Execution sur Grid distant"),
    ("options.add_argument('--headless=new')", "Mode headless CI"),
    ("driver.save_screenshot('f.png')", "Capture d'ecran"),
    ("driver.quit()", "Liberer la session"),
    ("pytest -n auto (xdist)", "Parallelisme via runner"),
  ],
  "concepts": [
    "Protocole W3C WebDriver : pilotage standardise de navigateurs reels, multi-langage.",
    "Attentes explicites (WebDriverWait/expected_conditions) indispensables (pas d'auto-wait natif).",
    "Selenium Grid (hub/nodes, ou Docker/Kubernetes) pour la distribution et le cross-browser.",
    "Page Object Model essentiel pour la maintenabilite (Selenium est bas niveau).",
    "Drivers geres (Selenium Manager) ; sessions a fermer (driver.quit()).",
    "S'integre a tout runner (pytest/JUnit/TestNG) et CI.",
  ],
  "install": [
    "Binding du langage + Selenium Manager ; Grid conteneurise (selenium/standalone-*).",
    "Page Object Model + waits explicites systematiques.",
    "Headless en CI ; resolution/locale fixees pour le determinisme.",
    "Grid sur Docker/Kubernetes pour le parallelisme.",
    "Selecteurs stables (data-*), pas de XPath fragile.",
  ],
  "cicd": [
    "Grid conteneurise (docker-compose/K8s) ephemere par pipeline.",
    "Parallelisme via runner (pytest-xdist/TestNG) + nodes Grid.",
    "Screenshots/logs d'echec archives ; rapport JUnit publie.",
    "Smoke en gate, matrice cross-browser en nocturne.",
    "Drivers/navigateurs epingles pour la reproductibilite.",
  ],
  "prod": [
    "Grid scalable (K8s) pour de larges matrices cross-browser.",
    "Waits explicites + POM = suites stables et maintenables.",
    "Sessions correctement liberees (pas de fuite de navigateurs).",
    "Parallelisme pour un feedback raisonnable malgre la lenteur intrinseque.",
    "Compatibilite navigateur suivie comme exigence qualite.",
  ],
  "security": [
    "Secrets via env/CI, jamais en dur.",
    "Donnees de test anonymisees ; environnements isoles.",
    "Grid non expose publiquement (acces restreint).",
    "Nettoyage des captures potentiellement sensibles.",
    "Navigateurs/drivers a jour (surface CVE).",
  ],
  "pitfalls": [
    "time.sleep au lieu d'attentes explicites : flaky/lent.",
    "XPath fragiles : preferer CSS/data-*.",
    "Sessions non fermees : fuite de ressources Grid.",
    "Pas de POM : maintenance ingerable.",
    "Drivers non epingles : builds non reproductibles.",
  ],
  "practices": [
    "Attentes explicites + Page Object Model.",
    "Grid conteneurise ephemere, parallelisme via runner.",
    "Selecteurs stables (data-*), headless deterministe.",
    "Drivers/navigateurs epingles, sessions liberees.",
    "Artefacts d'echec + JUnit en CI.",
  ],
},

"jmeter": {
  "name": "Apache JMeter", "category": "Tests automatises",
  "role": "Apache JMeter est l'outil open-source de reference pour les tests de performance et de charge (HTTP, API REST/SOAP, JDBC, JMS, etc.). Il simule des milliers d'utilisateurs virtuels, mesure latence, debit et taux d'erreur, et s'integre au CI pour detecter les regressions de performance. Concu pour valider la robustesse de microservices et d'outils IT a forte volumetrie (milliers d'utilisateurs, millions de transactions).",
  "commands": [
    ("jmeter -n -t plan.jmx -l res.jtl -e -o report/", "Test non-GUI + rapport HTML"),
    ("jmeter -n -t plan.jmx -Jusers=500 -Jrampup=60", "Parametrer la charge"),
    ("jmeter -g res.jtl -o report/", "Generer le rapport depuis des resultats"),
    ("jmeter -R worker1,worker2 -n -t plan.jmx", "Mode distribue (remote)"),
    ("jmeter-server", "Demarrer un noeud injecteur"),
    ("CSV Data Set Config", "Jeux de donnees parametres"),
    ("Constant Throughput Timer", "Controler le debit cible"),
    ("Assertions (Response/Duration)", "Criteres de succes/SLA"),
    ("Backend Listener -> InfluxDB/Prometheus", "Metriques live"),
    ("docker run justb4/jmeter ...", "Execution conteneurisee"),
    ("Summary/Aggregate Report", "Synthese des resultats"),
    ("-Jjmeter.save.saveservice.* ", "Configurer le format des resultats"),
  ],
  "concepts": [
    "Test Plan : Thread Group (utilisateurs/ramp-up) -> Samplers -> Timers -> Assertions -> Listeners.",
    "Toujours en mode non-GUI (-n) pour la charge reelle ; GUI uniquement pour concevoir.",
    "Metriques cles : latence (p90/p95/p99), throughput, taux d'erreur, percentiles > moyenne.",
    "Parametrage via CSV/variables ; correlation (extracteurs) pour les scenarios dynamiques.",
    "Mode distribue (controller + injecteurs) pour atteindre de hautes charges.",
    "Types : load, stress, soak/endurance, spike — objectifs distincts.",
  ],
  "install": [
    "JMeter + JDK ; plans .jmx versionnes, parametres externalises (pas de hardcode).",
    "Injecteurs conteneurises/distribues dimensionnes (le client ne doit pas etre le goulot).",
    "Backend Listener -> InfluxDB/Prometheus + Grafana pour le live.",
    "Profils de charge realistes (modele de trafic, pacing).",
    "Assertions SLA definies des la conception.",
  ],
  "cicd": [
    "Etape perf non-GUI : seuils SLA (p95/erreur) -> echec du pipeline si depasses (gate perf).",
    "Execution conteneurisee/distribuee orchestree par le pipeline.",
    "Rapport HTML + tendances archives ; comparaison vs baseline.",
    "Tests de charge nocturnes (longs) vs smoke perf par PR.",
    "Resultats pousses vers Grafana pour le suivi de tendance.",
  ],
  "prod": [
    "Soak tests pour detecter fuites memoire/degradations dans la duree.",
    "Charges realistes (pacing/throughput timer) — pas de boucle infinie irrealiste.",
    "Injecteurs distribues monitores (le client n'est pas le bottleneck).",
    "Correler resultats avec metriques serveur (Prometheus) pour la cause racine.",
    "Baselines de performance suivies comme KPI de release.",
  ],
  "security": [
    "Tests de charge uniquement sur environnements autorises (jamais prod sans accord).",
    "Secrets/jeux de donnees anonymises, hors du .jmx committe.",
    "Acces restreint aux injecteurs et resultats.",
    "Respect des quotas/limites pour ne pas provoquer de DoS involontaire.",
    "Donnees sensibles exclues des rapports.",
  ],
  "pitfalls": [
    "Tester en mode GUI : resultats faux/limite client.",
    "Injecteur sous-dimensionne : on mesure le client, pas le SUT.",
    "Se fier a la moyenne au lieu des percentiles.",
    "Pas de ramp-up/pacing : charge irrealiste.",
    "Secrets/donnees prod dans le plan.",
  ],
  "practices": [
    "Non-GUI (-n), percentiles (p95/p99) + taux d'erreur, baselines.",
    "Plans versionnes, parametres/donnees externalises et anonymises.",
    "Injecteurs distribues dimensionnes et monitores.",
    "Gate SLA en CI, tendances dans Grafana.",
    "Charges realistes (ramp-up/pacing), soak tests reguliers.",
  ],
},

"postman": {
  "name": "Postman", "category": "Tests automatises",
  "role": "Postman est la plateforme de developpement et de test d'API. Elle permet de concevoir, documenter, mocker et tester des API REST/SOAP/GraphQL via des Collections, des environnements et des scripts de test (Chai). Newman, son runner CLI, integre les collections aux pipelines CI pour des tests de contrat/regression automatises sur des services traitant de gros volumes transactionnels.",
  "commands": [
    ("newman run collection.json -e env.json", "Executer une collection en CI"),
    ("newman run c.json -r cli,junit,htmlextra", "Multi-rapports"),
    ("newman run c.json --env-var token=$T", "Injecter une variable"),
    ("newman run c.json -n 50 -d data.csv", "Iterations data-driven"),
    ("newman run c.json --bail", "Stopper au premier echec"),
    ("postman login --with-api-key $K", "CLI Postman"),
    ("postman collection run UID", "Lancer via Postman CLI"),
    ("pm.test('200', ()=>pm.response.to.have.status(200))", "Assertion de test"),
    ("pm.environment.set('token', v)", "Chainer des requetes"),
    ("pm.expect(json.id).to.eql(1)", "Assertion sur le corps"),
    ("npm i -g newman newman-reporter-htmlextra", "Installation"),
    ("docker run postman/newman run ...", "Execution conteneurisee"),
  ],
  "concepts": [
    "Collections = requetes organisees + scripts pre-request/test (JavaScript/Chai).",
    "Environnements/variables (globales/collection/env) pour parametrer sans dupliquer.",
    "Newman : runner CLI headless pour l'integration CI (memes collections).",
    "Data-driven : iterations sur CSV/JSON pour couvrir des jeux de donnees.",
    "Mock servers et documentation generee a partir des collections.",
    "Chainage : extraire une valeur d'une reponse et la reinjecter (workflows).",
  ],
  "install": [
    "Collections/environnements versionnes en Git (export JSON) — source de verite.",
    "Secrets via variables d'environnement/CI, jamais committes dans la collection.",
    "Newman + reporters (junit/htmlextra) ; execution conteneurisable.",
    "Structurer par service/domaine ; scripts de test reutilisables.",
    "Conventions d'assertions (statut, schema, SLA de reponse).",
  ],
  "cicd": [
    "newman run en CI avec env dedie : tests de contrat/regression API automatises.",
    "Rapports JUnit/HTML publies ; --bail pour un echec rapide.",
    "Data-driven (-d) pour valider de larges jeux de donnees.",
    "Gate de deploiement : smoke API avant promotion.",
    "Execution conteneurisee (postman/newman) reproductible.",
  ],
  "prod": [
    "Synthetic monitoring d'API (parcours critiques) rejoue en continu.",
    "Validation de schema/contrat pour prevenir les ruptures d'integration.",
    "Suites stables = signal de gate fiable.",
    "Tendances de temps de reponse suivies (SLA) comme KPI.",
    "Couverture des endpoints critiques tracee.",
  ],
  "security": [
    "Secrets/tokens via variables d'environnement/CI, jamais dans la collection committee.",
    "Donnees de test anonymisees ; pas de cible prod sans accord.",
    "Reduction des scopes des tokens de test ; rotation.",
    "Nettoyage des rapports (pas de PII/jetons).",
    "Acces aux environnements de test au moindre privilege.",
  ],
  "pitfalls": [
    "Tokens/secrets committes dans la collection.",
    "Pas de versionnement (collections dans le cloud uniquement) : derive.",
    "Tests sans assertions (juste des appels) : faux signal.",
    "Environnements non parametres (URLs en dur).",
    "Pas de Newman : tests non integres au CI.",
  ],
  "practices": [
    "Collections/env versionnes en Git, secrets externalises.",
    "Assertions reelles (statut/schema/SLA), data-driven.",
    "Newman + reporters JUnit/HTML en CI, --bail.",
    "Execution conteneurisee reproductible.",
    "Synthetic monitoring + suivi des tendances SLA.",
  ],
},
}
